import { db } from "@workspace/db";
import {
  companiesTable,
  sheiCardsTable,
  signalsTable,
  benchmarksTable,
  playbookSectionsTable,
} from "@workspace/db";

export async function seedDatabase() {
  const existingCompanies = await db.select().from(companiesTable);
  if (existingCompanies.length > 0) return;

  await db.insert(companiesTable).values([
    {
      name: "HUL",
      fullName: "Hindustan Unilever Limited",
      tier: 1,
      geography: "INDIA",
      exchange: "BSE/NSE",
      irPage: "hul.co.in/investors",
      earningsCadence: "Quarterly",
      revenue: "~₹15,200 Cr (Q3 FY25)",
      revenueGrowth: "~2-3% YoY",
      ebitdaMargin: "~23-24%",
      marketCap: "~₹5.5 lakh Cr",
      categories: "Home Care, Beauty & Personal Care, Foods & Refreshment",
      strategicPriorities: "**Priority 1: Premiumization** — Moving portfolio mix toward higher-margin premium SKUs (Dove, Indulekha, Horlicks, Vaseline).\n\n**Priority 2: Go-to-Market Reinvention** — Redesigning route-to-market to accommodate quick-commerce (Blinkit, Zepto, Swiggy Instamart) as a serious channel.\n\n**Priority 3: Sustainability-Linked SC** — Committed to carbon neutrality and plastic reduction targets materially impacting SC design.",
      scIntelligence: "**SC Transformation:** Mid-way through a multi-year SC transformation — demand-driven replenishment (push to pull in general trade) and manufacturing network optimization.\n\n**Manufacturing:** ~40 facilities. Ongoing rationalization. Increasing outsourcing of lower-value SKUs.\n\n**Distribution:** ~3,500 redistribution stockists serving ~8M retail outlets. Piloting direct-to-retailer (DTR) model in urban markets.\n\n**Working Capital:** Runs negative working capital. Under pressure as modern trade and q-commerce channels have different payment terms.\n\n**Known Challenges:** Rural last-mile reach declining; cold chain capability limited for Foods portfolio; Horlicks SC integration not fully complete.",
      techIntelligence: "**ERP:** Running SAP as core ERP. SAP S/4HANA migration in progress.\n\n**GenAI:** Piloted AI-based demand forecasting in select categories. GenAI explored for consumer insights and trade promotion optimization.\n\n**Digital Commerce:** E-commerce ~15-16% of revenues. Quick-commerce growing 40%+ YoY.\n\n**Partnerships:** Unilever global partnerships with Google Cloud, Microsoft Azure.",
      openProblems: "**Problem 1: RTM Model Redundancy**\nObservation: Traditional 3,500-stockist RTM model designed for general trade dominance in a pre-quick-commerce era.\nMetric: General trade revenue flat/negative; modern trade + e-commerce growing 15-40%.\nThoucentric Angle: RTM design and channel strategy transformation — redesigning coverage models, stockist economics, DTR viability assessment.\n\n**Problem 2: Demand Forecasting Degradation**\nObservation: Planning cycle mismatch — monthly forecast model managing a 4-hour fulfillment channel.\nMetric: Forecast accuracy declining in digital-heavy categories; aging inventory building in Foods.\nThoucentric Angle: Demand Sensing Diagnostic → S&OP Redesign → Sensing Layer Implementation.",
      quickTake: "HUL is navigating a structural deceleration in rural consumption while defending its premium urban portfolio — a dual-speed challenge compressing margins and forcing a rethink of go-to-market. The RTM transformation and quick-commerce readiness are the critical execution tests. For any consultant engaging FMCG clients, HUL's distribution reinvention is the sector's most important real-time case study.",
      confidence: "HIGH",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "Unilever",
      fullName: "Unilever PLC",
      tier: 1,
      geography: "GLOBAL",
      exchange: "LSE/NYSE",
      irPage: "investors.unilever.com",
      earningsCadence: "Quarterly",
      revenue: "€59.6B (FY24)",
      revenueGrowth: "~4% underlying sales growth",
      ebitdaMargin: "~17-18%",
      marketCap: "~£38B",
      categories: "Beauty & Wellbeing, Personal Care, Home Care, Nutrition, Ice Cream",
      strategicPriorities: "**Priority 1: Portfolio Simplification** — Separating Ice Cream business (Ben & Jerry's, Magnum, Walls). Focusing on core categories.\n\n**Priority 2: Power Brands** — Focus on 30 power brands that represent ~75% of revenue.\n\n**Priority 3: Productivity Programme** — €800M cost-saving program driving restructuring and headcount reduction.",
      scIntelligence: "**SC Transformation:** Global SC transformation program led by CSCO. Demand sensing reinvestment acknowledged in 2024 Investor Day.\n\n**Manufacturing:** 300+ manufacturing sites globally. Ongoing network rationalization.\n\n**Technology:** Advanced SC technology stack — AI-powered demand sensing, integrated planning platforms.\n\n**Known Challenges:** Demand sensing model required 'significant recalibration' post-2023. Channel proliferation adding complexity.",
      techIntelligence: "**ERP:** SAP S/4HANA fully deployed globally.\n\n**AI/SC:** Demand sensing platform with external signal integration (social data, weather, POS feeds).\n\n**Cloud:** Google Cloud and Microsoft Azure for data infrastructure.\n\n**GenAI:** D-A range on most technology dimensions.",
      openProblems: "**Problem 1: Ice Cream Separation Complexity**\nObservation: Separating a €7.9B business with a distinct cold-chain SC requirement.\nThoucentric Angle: SC separation design and stand-up advisory.\n\n**Problem 2: Demand Sensing Architecture**\nObservation: Acknowledged recalibration required across multiple markets post-channel proliferation.\nThoucentric Angle: Demand sensing diagnostic and architecture redesign.",
      quickTake: "Unilever is executing the most significant portfolio simplification in a decade — the Ice Cream separation signals a clear intent to focus on fewer, stronger categories. The productivity programme is structural, not cyclical. As the global SC benchmark for India FMCG players, Unilever's demand sensing investments are 3-5 years ahead of the India market — and the gap is the consulting opportunity.",
      confidence: "HIGH",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "P&G",
      fullName: "Procter & Gamble",
      tier: 1,
      geography: "GLOBAL",
      exchange: "NYSE",
      irPage: "pginvestor.com",
      earningsCadence: "Quarterly",
      revenue: "$84B (FY24)",
      revenueGrowth: "~3% organic",
      ebitdaMargin: "~24-26%",
      marketCap: "~$380B",
      categories: "Beauty, Grooming, Health Care, Fabric & Home Care, Baby, Feminine & Family Care",
      strategicPriorities: "**Priority 1: Innovation-Led Growth** — Continuous innovation in premium tiers across all categories.\n\n**Priority 2: Superiority** — Product, packaging, communication, retail execution, and value superiority across all 10 categories.\n\n**Priority 3: Productivity** — Ongoing cost productivity program funding reinvestment.",
      scIntelligence: "**SC Excellence:** Ranked #1 in Gartner Supply Chain Top 25 for 9 of past 12 years.\n\n**Demand Sensing:** Proprietary demand sensing platform integrating POS data, social signals, and weather data.\n\n**OTIF:** >95% to retail customers. Benchmark setter globally.\n\n**Forecast Accuracy:** >85% at category level.",
      techIntelligence: "**ERP:** SAP fully deployed globally.\n\n**AI:** 50+ deployed GenAI use cases as of 2024.\n\n**Partnerships:** Google Cloud for demand sensing and data infrastructure.\n\n**Innovation:** AI in demand sensing, trade promotion optimization, and manufacturing.",
      openProblems: "**Problem 1: Emerging Market SC Complexity**\nObservation: India and Southeast Asia distribution complexity growing as channels fragment.\nThoucentric Angle: India GTM advisory for P&G vendor ecosystem.\n\n**Problem 2: Channel Proliferation Risk**\nObservation: Management cited 'channel proliferation risk' as a planning challenge despite high OTIF.\nThoucentric Angle: Demand sensing architecture for high-complexity markets.",
      quickTake: "P&G is the global benchmark for FMCG supply chain and innovation. With 50+ GenAI deployments and demand sensing at >85% accuracy, it is 5-8 years ahead of India mid-tier. Every diagnostic with an Indian FMCG client should reference P&G benchmarks — the gap quantifies the opportunity.",
      confidence: "HIGH",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "Nestlé",
      fullName: "Nestlé S.A.",
      tier: 1,
      geography: "GLOBAL",
      exchange: "SIX Swiss Exchange",
      irPage: "nestle.com/investors",
      earningsCadence: "Quarterly",
      revenue: "CHF 91.4B (FY24)",
      revenueGrowth: "~2.2% organic (decelerating)",
      ebitdaMargin: "~17.4%",
      marketCap: "~CHF 220B",
      categories: "Powdered & Liquid Beverages, Pet Care, Nutrition & Health Science, Prepared Dishes, Confectionery, Dairy",
      strategicPriorities: "**Priority 1: Portfolio Reshaping** — Divesting underperforming brands, investing behind growth categories (PetCare, Coffee, Health Science).\n\n**Priority 2: Pricing & Volume Balance** — Managing the transition from price-driven to volume-driven growth post-inflationary period.\n\n**Priority 3: Operational Efficiency** — CHF 2.5B savings program announced under new CEO Laurent Freixe.",
      scIntelligence: "**SC Technology:** Advanced demand planning using SAP IBP. AI in procurement for supplier risk monitoring.\n\n**Manufacturing:** 449 factories globally. Simplification underway.\n\n**Forecast Accuracy:** Stable; attributed to product portfolio concentration in fewer, more predictable categories.",
      techIntelligence: "**AI:** Deployed AI in procurement (supplier risk monitoring), SC (demand sensing), and R&D (formulation assistance).\n\n**ERP:** SAP globally deployed.\n\n**Innovation:** Strong AI deployment in R&D — formula optimization and consumer insights.",
      openProblems: "**Problem 1: India Portfolio Optimization**\nObservation: India category portfolio (Maggi, KitKat, Nescafé) growing strongly but distribution depth lagging vs. category potential.\nThoucentric Angle: Distribution expansion advisory and coverage model design.\n\n**Problem 2: Price-Volume Rebalancing**\nObservation: Transitioning from 10%+ pricing to volume-driven growth after 2 years of price increases.\nThoucentric Angle: Trade promotion optimization to drive volume without margin dilution.",
      quickTake: "Nestlé is in a strategic reset under new CEO Laurent Freixe, focused on portfolio simplification and operational efficiency after years of underperformance. Counter-intuitively, their stable forecast accuracy (vs. peers struggling) comes from product concentration — a data point useful in SC diagnostic conversations.",
      confidence: "MEDIUM",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "ITC",
      fullName: "ITC Limited",
      tier: 1,
      geography: "INDIA",
      exchange: "BSE/NSE",
      irPage: "itcportal.com/investor-zone",
      earningsCadence: "Quarterly",
      revenue: "~₹18,800 Cr FMCG (FY24)",
      revenueGrowth: "~7-8% (FMCG segment)",
      ebitdaMargin: "~58% (Foods division gross margin)",
      marketCap: "~₹5.6 lakh Cr",
      categories: "Foods (Aashirvaad, Sunfeast, Yippee), Personal Care (Fiama, Vivel), Education & Stationery, Agri",
      strategicPriorities: "**Priority 1: FMCG Scale-Up** — Accelerating FMCG revenue to ₹1 lakh Cr target. Focus on distribution deepening.\n\n**Priority 2: Agri-Business Integration** — Leveraging e-Choupal network and backward integration to build SC advantage.\n\n**Priority 3: Premium Portfolio** — Extending Aashirvaad and Sunfeast into premium adjacencies.",
      scIntelligence: "**SC Advantage:** Unique SC built on backward integration (agri sourcing through e-Choupal — 6,500 kiosks, 40,000 villages).\n\n**Distribution:** Building direct distribution; DMS deployed across network.\n\n**Manufacturing:** 70+ factories across India for FMCG.",
      techIntelligence: "**ERP:** SAP migration in progress (S/4HANA).\n\n**DMS:** Deployed across distributor network.\n\n**GenAI:** Nascent; limited public disclosures on specific deployments.",
      openProblems: "**Problem 1: Urban Modern Trade Execution**\nObservation: General trade strength not translating to modern trade and e-commerce execution quality.\nThoucentric Angle: Modern trade key account management and e-commerce channel strategy.\n\n**Problem 2: SC Technology Catch-Up**\nObservation: S/4HANA migration in progress; planning layer fragmented relative to scale.\nThoucentric Angle: SC technology roadmap design and S/4HANA implementation advisory.",
      quickTake: "ITC's FMCG segment is a genuine challenger to HUL's dominance — uniquely backed by agri backward integration through e-Choupal that no other player can replicate. The FMCG revenue trajectory is strong, but technology maturity lags ambition. The S/4HANA migration is the critical enabler for the next growth phase.",
      confidence: "HIGH",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "Dabur",
      fullName: "Dabur India Limited",
      tier: 1,
      geography: "INDIA",
      exchange: "BSE/NSE",
      irPage: "dabur.com/investors",
      earningsCadence: "Quarterly",
      revenue: "~₹3,100 Cr (Q3 FY25)",
      revenueGrowth: "~5-6% YoY",
      ebitdaMargin: "~18-19%",
      marketCap: "~₹85,000 Cr",
      categories: "Healthcare (Chyawanprash, Hajmola), Hair Care (Vatika, Amla), Oral Care, Skin Care, Home Care, Foods (Real juices)",
      strategicPriorities: "**Priority 1: Naturals Premium** — Doubling down on Ayurvedic/natural positioning across categories.\n\n**Priority 2: International Expansion** — Middle East, Africa, and South Asia markets growing double-digit.\n\n**Priority 3: Rural Recovery** — Investing in rural distribution as urban channels fragment.",
      scIntelligence: "**SC Challenges:** ERP landscape fragmented (multiple regional ERPs, S/4HANA migration pending).\n\n**Forecasting:** Over-forecasting in seasonal categories driven by rural demand miss.\n\n**Distribution:** GT-heavy; building DMS capability. Modern trade and e-commerce lagging peers.",
      techIntelligence: "**ERP:** Fragmented; S/4HANA migration pending.\n\n**AI/GenAI:** Annual report FY24 mentions AI/ML for consumer insights. No specific deployed use cases disclosed.\n\n**Digital Commerce:** Growing from small base; ~5-8% estimated.",
      openProblems: "**Problem 1: GenAI Readiness Gap**\nObservation: Board mandate for AI transformation; infrastructure prerequisites not in place.\nMetric: 74% of FMCG technology leaders cite data quality as primary AI blocker.\nThoucentric Angle: GenAI Readiness Assessment → Data Foundation Build → Use Case Implementation.\n\n**Problem 2: SC Technology Debt**\nObservation: Fragmented ERP landscape preventing integrated planning.\nThoucentric Angle: Technology landscape assessment → ERP harmonization roadmap.",
      quickTake: "Dabur represents the classic Indian FMCG mid-tier challenge: strong brands with deep heritage, but technology and SC infrastructure not keeping pace with growth ambitions. The GenAI announcement trap is most visible here — board mandate, working group, no deployed use cases. This is exactly the consulting entry point Thoucentric should target.",
      confidence: "MEDIUM",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "Marico",
      fullName: "Marico Limited",
      tier: 1,
      geography: "INDIA",
      exchange: "BSE/NSE",
      irPage: "maricoindia.com/investor-relations",
      earningsCadence: "Quarterly",
      revenue: "~₹2,700 Cr (Q3 FY25)",
      revenueGrowth: "~6-8% YoY",
      ebitdaMargin: "~17-18%",
      marketCap: "~₹65,000 Cr",
      categories: "Hair Care (Parachute, Hair & Care), Healthcare (Saffola), Male Grooming (Set Wet), Foods",
      strategicPriorities: "**Priority 1: Saffola Diversification** — Extending Saffola into healthy snacking, oats, and premium foods.\n\n**Priority 2: International Markets** — Bangladesh, Vietnam, South Africa, Middle East all growing.\n\n**Priority 3: Digital-First Brands** — Building direct-to-consumer brands (True Elements, Beardo).",
      scIntelligence: "**Forecasting:** Over-forecasting in Parachute (coconut oil) driven by rural demand miss resulted in inventory days uptick in FY24.\n\n**Distribution:** Strong in traditional trade; building modern trade and digital capability.\n\n**DMS:** Deployed (MTCP mobile app for field sales). Advanced planning AI not evident.",
      techIntelligence: "**ERP:** Deployed but not S/4HANA.\n\n**DMS:** MTCP (mobile order taking app) deployed; strong field sales digitization.\n\n**GenAI:** CTO references digital transformation including AI. No specific SC AI use cases.\n\n**Tech Maturity:** L-D range on most advanced technology dimensions.",
      openProblems: "**Problem 1: Demand Forecasting in Seasonal Categories**\nObservation: Parachute coconut oil demand highly seasonal and rural-driven; traditional forecasting models failing.\nThoucentric Angle: Demand sensing redesign for seasonal commodity categories.\n\n**Problem 2: Digital Channel SC Readiness**\nObservation: D2C brands (True Elements, Beardo) running on separate SC infrastructure.\nThoucentric Angle: Integrated omnichannel SC design for digital-first portfolio.",
      quickTake: "Marico is executing a quiet but important transformation — diversifying from a single-category dependency (Parachute) to a portfolio play with D2C and foods. The SC and technology gap is real but the company has demonstrated willingness to invest. The demand forecasting issue in core coconut oil is a quantified, immediate entry point.",
      confidence: "MEDIUM",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "Godrej CP",
      fullName: "Godrej Consumer Products",
      tier: 1,
      geography: "INDIA",
      exchange: "BSE/NSE",
      irPage: "godrejcp.com/investors",
      earningsCadence: "Quarterly",
      revenue: "~₹3,800 Cr (Q3 FY25)",
      revenueGrowth: "~8-10% YoY",
      ebitdaMargin: "~20-21%",
      marketCap: "~₹95,000 Cr",
      categories: "Home Care (HIT, Good Knight), Personal Wash (Godrej No. 1), Hair Color (Godrej Expert), Air Fresheners",
      strategicPriorities: "**Priority 1: India Rural Penetration** — Deepening distribution in rural markets; targeting 50% rural revenue.\n\n**Priority 2: Africa Expansion** — Africa contributing 20%+ revenue; scaling household insecticide leadership.\n\n**Priority 3: Innovation Pipeline** — New product launches across home care and personal care.",
      scIntelligence: "**Distribution:** Strong rural network. ~1,300+ distributors. Building direct reach.\n\n**SC Technology:** DMS deployed across India network.\n\n**International SC:** Complex multi-geography SC across India, Indonesia, Africa.",
      techIntelligence: "**GenAI:** Investor day materials reference GenAI for marketing optimization. SC AI use cases not mentioned.\n\n**ERP:** Not disclosed publicly; likely SAP for core.\n\n**Tech Maturity:** Limited on advanced planning dimensions.",
      openProblems: "**Problem 1: Africa SC Complexity**\nObservation: Growing Africa business running on separate systems with limited integration.\nThoucentric Angle: Cross-geography SC integration and regional planning design.\n\n**Problem 2: Rural Last-Mile Optimization**\nObservation: Rural distribution critical for growth but cost-to-serve economics challenging.\nThoucentric Angle: Rural RTM optimization and distributor productivity improvement.",
      quickTake: "Godrej CP is one of India's most underappreciated FMCG businesses — strong growth, category leadership in household insecticides, and an emerging Africa story. The SC complexity is real but manageable. Technology modernization is the priority gap that creates the clearest consulting entry.",
      confidence: "MEDIUM",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
  ]);

  await db.insert(sheiCardsTable).values([
    {
      cardId: "SHEI-2025-Q2-01",
      title: "The Demand Forecasting Collapse in Modern-Channel FMCG",
      functionTag: "SUPPLY_CHAIN",
      geographyTag: "BOTH",
      urgency: "IMMEDIATE",
      signal: "FMCG companies globally are reporting growing inventory distortion — the gap between what demand planning predicted and what actually sold is widening, not narrowing, despite investments in planning technology. HUL management noted in Q3 FY25 that quick-commerce channel demand patterns are 'fundamentally different' from general trade. Unilever's global SC team publicly acknowledged that their demand sensing models required 'significant recalibration' post-2023. P&G reported OTIF improvement (94%+) but simultaneously cited 'channel proliferation risk' as a top planning challenge.",
      hypothesis: "Traditional statistical demand forecasting — built for monthly or weekly general trade replenishment cycles — is structurally incompatible with the 4-hour fulfillment rhythms of quick-commerce and the viral, social-media-driven demand spikes of modern FMCG. FMCG companies that do not rebuild their demand sensing architecture around external signal integration will see forecast accuracy degrade by 10-15 percentage points over the next 2-3 years as modern channels grow to 25-40% of revenue.",
      evidence: "HUL (India): Digital channels ~15-16% of revenue; quick-commerce growing 40%+ YoY. Planning cycle mismatch acknowledged. Aging inventory in Foods segment.\n\nUnilever (Global): Demand sensing reinvestment acknowledged. Estimated forecast accuracy below 75% at category level for some markets.\n\nP&G (Global): Improving OTIF (94%+) but cited 'channel proliferation risk.' Invested in AI-based demand sensing with Google Cloud.\n\nMarico (India): Over-forecasting in Parachute driven by rural demand miss; inventory days uptick in FY24.\n\nCounter-evidence: Nestlé reports stable forecast accuracy — attributed to product portfolio concentration. The problem is amplified by high-SKU complexity.",
      clientImplication: "CPOs and CSCOs need to make a fundamental architecture decision: continue optimizing the existing time-series forecasting engine (diminishing returns) or invest in a new demand sensing layer that ingests external signals in near-real-time. The window for this decision is 12-18 months before modern-channel growth makes the current architecture untenable. Companies that wait will face simultaneous inventory excess and stockout problems.",
      thoucentriqAngle: "3-phase engagement: (1) Demand Sensing Diagnostic — 4-6 weeks assessing forecast accuracy by channel, SKU, and region; identifying failure modes and quantifying revenue and inventory cost impact. (2) Architecture Design — defining future demand sensing model, technology selection (o9, Kinaxis, or build-on-ERP), data sourcing strategy. (3) Implementation Advisory — program management of the sensing layer build, change management for new S&OP cadence.",
      pitchAnchor: "We have been tracking a consistent pattern across seven FMCG companies this quarter: demand forecast accuracy is declining despite technology investment, and the common thread is quick-commerce. HUL's planning team is effectively using a monthly forecast model to manage a 4-hour fulfillment channel — and they are not alone. The companies pulling ahead, like P&G, are rebuilding their demand sensing layer around external signals: social data, weather, POS feeds. We have designed a diagnostic that identifies the specific failure modes in 4-6 weeks and gives you a quantified business case for the architecture change.",
      provocQuestion: "If quick-commerce reaches 30% of your revenue in three years, how many days of inventory buffer are you carrying today that you won't be able to afford then?",
      povParagraph: "We believe the demand planning crisis in FMCG is misdiagnosed. Most companies are treating it as a technology problem — better algorithms, more data — when the real issue is architectural. Statistical forecasting was designed for a world of weekly replenishment cycles and stable retail channels. Quick-commerce has a four-hour fulfillment clock. Social media can move 10,000 units of a product overnight. The companies getting ahead of this — P&G with Google Cloud, a handful of European FMCG players — are not just buying better software. They are rebuilding the sensing layer: integrating social listening, POS data, weather events, and promotional calendars into a real-time signal feed. The companies that don't make this architecture shift in the next 18 months will face a compounding problem: declining accuracy, rising inventory costs, and lost shelf space as their OTIF deteriorates.",
      version: "1.0",
      nextReview: "2025-07-01",
    },
    {
      cardId: "SHEI-2025-Q2-02",
      title: "The GenAI Implementation Gap in Indian FMCG",
      functionTag: "IT_TECHNOLOGY",
      geographyTag: "INDIA",
      urgency: "MEDIUM_TERM",
      signal: "Indian FMCG mid-tier players (Dabur, Marico, Godrej CP, Emami, Britannia) are universally announcing GenAI exploration initiatives in annual reports and investor calls, but concrete deployed use cases with measurable outcomes remain rare. In contrast, global peers are 2-3 years ahead in actual deployment. The gap is not ambition — virtually every India FMCG CXO has a GenAI task force. The gap is in the infrastructure prerequisites: clean data, process standardization, and integrated ERP landscapes.",
      hypothesis: "Indian FMCG companies are in a GenAI 'announcement trap' — publicly committing to AI transformation while privately lacking the foundational data and process infrastructure that makes GenAI deployments viable. Without addressing data quality, ERP fragmentation, and SC process standardization first, GenAI pilots will remain pilots. This creates a predictable 18-24 month implementation crisis for most mid-tier Indian FMCG companies as leadership pressure to show GenAI ROI intensifies.",
      evidence: "Dabur: Annual report FY24 mentions AI/ML for consumer insights. No specific deployed use cases disclosed. ERP landscape fragmented.\n\nMarico: CTO references digital transformation including AI; deployed mobile order taking app but advanced planning AI not evident.\n\nGodrej CP: Investor day materials reference GenAI for marketing optimization. SC AI use cases not mentioned.\n\nHUL (positive counter-example): More advanced; demand forecasting AI pilots acknowledged; benefiting from Unilever global technology infrastructure.\n\nGlobal benchmark: P&G has 50+ deployed GenAI use cases as of 2024. Nestlé has AI in procurement, SC, and R&D. Indian mid-tier players at 1-3 pilots.\n\nRoot cause: Deloitte survey found 74% of Indian FMCG technology leaders cite data quality as primary blocker to AI deployment.",
      clientImplication: "CTOs and CDOs at Indian FMCG mid-tier companies face a two-track problem: (1) Board/leadership expectation of GenAI progress, and (2) Infrastructure reality making meaningful deployment 18-36 months away without foundational remediation. The strategic choice: continue running pilots that produce press releases, or make the harder investment in data infrastructure that enables durable AI deployment.",
      thoucentriqAngle: "Three engagement types: (1) GenAI Readiness Assessment (4-6 weeks): evaluate data infrastructure, process maturity, and organizational readiness across 12 highest-priority use cases. Produces prioritized roadmap with honest timelines. (2) Data Foundation Build: working with CTO team on data lake architecture, master data quality, and integration layer. (3) GenAI Use Case Implementation: deploying specific high-ROI use cases once foundation is ready — demand sensing, trade promotion optimization, supplier risk monitoring.",
      pitchAnchor: "Every Indian FMCG CXO we speak with has a GenAI task force and a board mandate for AI transformation. Almost none have deployed at scale, and when we dig into why, the answer is consistently the same: the data infrastructure required for GenAI to work is not there. The global leaders — P&G has 50 deployed use cases, Nestlé is running AI in procurement, demand sensing, and R&D simultaneously — spent 3-4 years building their data foundations before the AI layer became viable. The Indian mid-tier is skipping that step and wondering why their pilots aren't scaling. We have a 6-week readiness assessment that tells you exactly what foundation work is needed and in what sequence.",
      provocQuestion: "How many of your GenAI pilots from last year are now running in production, and what revenue or cost impact have you measured?",
      povParagraph: "We believe the Indian FMCG GenAI moment is 18 months away — but only for companies that start the prerequisite work now. Most mid-tier Indian FMCG companies are in the same position: a board mandate for AI, a working group exploring use cases, and a data infrastructure built for a different era. The companies that will close the gap with global peers are not the ones running the most pilots — they are the ones making the unsexy investments in data quality, ERP modernization, and process standardization that are the actual prerequisites for AI to work. We call this the GenAI readiness problem, and it is the most consistent pattern we see across the sector.",
      version: "1.0",
      nextReview: "2025-10-01",
    },
    {
      cardId: "SHEI-2025-Q2-03",
      title: "India FMCG Route-to-Market Model at Structural Inflection",
      functionTag: "SALES_DISTRIBUTION",
      geographyTag: "INDIA",
      urgency: "IMMEDIATE",
      signal: "India's traditional FMCG distribution model — built on a chain of distributors, sub-distributors, and 12 million kirana stores — is experiencing structural stress from multiple directions simultaneously. Quick-commerce platforms (Blinkit, Zepto, Swiggy Instamart) are growing 40-60% YoY and now represent 10-20% of urban FMCG revenue. HUL's distributor EBITDA is declining as the high-value urban outlet base migrates to quick-commerce. Multiple India FMCG players have announced 'direct-to-retailer' pilots, signaling loss of confidence in the traditional stockist model.",
      hypothesis: "The traditional India FMCG distributor/stockist model is economically non-viable for urban geographies as quick-commerce and D2C erode the high-value outlet base, leaving distributors with declining throughput and rising cost-to-serve. Companies that do not redesign their urban RTM model in the next 18-24 months will face a simultaneous decline in revenue quality and distribution cost efficiency.",
      evidence: "HUL: 3,500+ redistribution stockists. General trade revenue flat/negative in urban markets. Direct-to-retailer pilot announced in select cities.\n\nITC: Accelerating direct distribution investment. e-Choupal network provides rural advantage but urban model under pressure.\n\nMarico: Distribution throughput metrics declining in urban premium outlets as channels shift.\n\nDabur: High trade spend (estimated 18-22% of revenue in some channels) with declining volume response in urban markets.\n\nQuick-commerce data: Blinkit, Zepto, Swiggy Instamart collectively growing 50%+ YoY from a significant base. Urban kirana store foot traffic declining 15-20% YoY according to Nielsen retail audit data.",
      clientImplication: "CSCOs and Sales Directors face a structural decision: redesign urban RTM now with first-mover advantage, or wait and face forced redesign at higher cost as distributor economics deteriorate. The decision involves redesigning coverage models, stockist economics, channel P&L tracking, and direct-to-retailer investment. This is a 12-24 month transformation, not a quick fix.",
      thoucentriqAngle: "Classic S&D transformation engagement: (1) Coverage Model Diagnostic — assess current distributor economics, outlet-level profitability, and channel shift patterns in 3-4 representative cities. (2) RTM Architecture Design — design the future model: which outlets go direct, which stay through stockist, which channels get dedicated GTM teams. (3) Implementation Support — pilot design, distributor transition management, technology enablement (DMS upgrade, route optimization).",
      pitchAnchor: "We have been tracking distributor EBITDA trends across India FMCG for three quarters, and the data is consistent: in urban markets, the traditional stockist model is losing its economic rationale. The high-value outlets — premium supermarkets, large-format modern trade, high-footfall kirana stores — are increasingly served by quick-commerce platforms at unit economics the distributor cannot match. The companies that will win the next decade are the ones redesigning their urban RTM right now, not after the model has fully broken. We have built a coverage model diagnostic that tells you exactly where the model is breaking and what the future architecture should look like.",
      provocQuestion: "What percentage of your top 1,000 revenue-generating outlets in Mumbai or Delhi are now also served by at least one quick-commerce platform, and what has happened to your average order value in those outlets over the last 4 quarters?",
      povParagraph: "The India FMCG route-to-market model that drove three decades of growth is at a structural inflection point. The distributor/stockist chain was built for a world where the only way to reach 12 million kirana stores was through a layered intermediary network. Quick-commerce has demonstrated that urban consumers will pay a premium for 10-minute delivery, and in doing so, it has fundamentally changed the economics of the traditional high-value outlet. The companies that recognize this as a structural shift — not a temporary disruption — and redesign their urban coverage models now will have a significant first-mover advantage. The ones that wait will find their distributors renegotiating margins, their best outlet relationships migrating to platforms, and their RTM cost structure built for a channel mix that no longer exists.",
      version: "1.0",
      nextReview: "2025-07-01",
    },
  ]);

  await db.insert(signalsTable).values([
    {
      companyName: "HUL",
      category: "STRATEGY",
      summary: "HUL announces pilot of direct-to-retailer model in Mumbai bypassing stockist layer in select urban pincodes",
      strength: "HIGH",
      action: "SHEI_CANDIDATE",
      source: "BSE Filing Q3 FY25",
    },
    {
      companyName: "Dabur",
      category: "TECHNOLOGY",
      summary: "Dabur forms AI task force and announces GenAI pilot for consumer insights — no deployed use cases disclosed",
      strength: "MEDIUM",
      action: "UPDATE_CARD",
      source: "Dabur Annual Report FY24",
    },
    {
      companyName: "P&G",
      category: "TECHNOLOGY",
      summary: "P&G reaches 50+ deployed GenAI use cases globally; Google Cloud partnership deepened for demand sensing",
      strength: "HIGH",
      action: "SHEI_CANDIDATE",
      source: "P&G Investor Day 2024",
    },
    {
      companyName: "Unilever",
      category: "SUPPLY_CHAIN",
      summary: "Unilever acknowledges demand sensing models required 'significant recalibration' post-2023 due to channel proliferation",
      strength: "HIGH",
      action: "SHEI_CANDIDATE",
      source: "Unilever Investor Day 2024",
    },
    {
      companyName: "ITC",
      category: "STRATEGY",
      summary: "ITC FMCG segment posts 8.2% revenue growth; management signals ₹1 lakh Cr FMCG target remains on track",
      strength: "MEDIUM",
      action: "UPDATE_CARD",
      source: "ITC Q3 FY25 Earnings Call",
    },
    {
      companyName: "Marico",
      category: "EARNINGS",
      summary: "Marico reports inventory days uptick in Parachute segment due to rural demand miss; management flags forecasting model limitations",
      strength: "HIGH",
      action: "UPDATE_CARD",
      source: "Marico Q3 FY25 Earnings Transcript",
    },
    {
      companyName: "Nestlé",
      category: "STRATEGY",
      summary: "New CEO Laurent Freixe announces CHF 2.5B cost savings program and portfolio simplification — exits underperforming brands",
      strength: "HIGH",
      action: "DISRUPTION_BRIEF",
      source: "Nestlé FY24 Results",
    },
    {
      companyName: "Godrej CP",
      category: "EARNINGS",
      summary: "Godrej CP Q3 FY25 revenue grows 9.2% driven by Africa and Indonesia; India urban portfolio under competitive pressure",
      strength: "MEDIUM",
      action: "UPDATE_CARD",
      source: "Godrej CP Q3 FY25 Earnings",
    },
    {
      companyName: "MULTI-COMPANY",
      category: "DISRUPTION",
      summary: "Quick-commerce platforms (Blinkit, Zepto, Instamart) collectively cross ₹30,000 Cr annualized GMV — India FMCG distribution structural shift accelerates",
      strength: "HIGH",
      action: "SHEI_CANDIDATE",
      source: "Industry Reports Q4 2024",
    },
    {
      companyName: "HUL",
      category: "REGULATORY",
      summary: "FSSAI announces updated packaging regulations for foods segment — requires labeling changes across 200+ HUL SKUs by Q3 FY26",
      strength: "MEDIUM",
      action: "UPDATE_CARD",
      source: "FSSAI Gazette Notification",
    },
  ]);

  await db.insert(benchmarksTable).values([
    {
      kpiName: "Forecast Accuracy (%)",
      definition: "(1 - MAPE) at 4-week horizon",
      functionTag: "SUPPLY_CHAIN",
      bestInClass: "80-88%",
      industryMedian: "65-75%",
      laggard: "<55%",
      indiaContext: "India estimated 55-70% for most players; quick-commerce making it worse",
      sheiAnnotation: "Signal: Promo-driven demand spikes → Hypothesis: Traditional time-series forecasting architecturally broken for modern FMCG",
      version: "1.0",
    },
    {
      kpiName: "OTIF (%)",
      definition: "On-Time In-Full delivery to retail/distributor",
      functionTag: "SUPPLY_CHAIN",
      bestInClass: "90-96%",
      industryMedian: "80-88%",
      laggard: "<72%",
      indiaContext: "India general trade OTIF often 70-80% due to distributor variability",
      sheiAnnotation: "Low OTIF = revenue leakage + lost shelf space; most clients undertrack this",
      version: "1.0",
    },
    {
      kpiName: "Inventory Days",
      definition: "Average inventory / (COGS/365)",
      functionTag: "SUPPLY_CHAIN",
      bestInClass: "28-40 days",
      industryMedian: "45-65 days",
      laggard: ">90 days",
      indiaContext: "HUL ~45 days; regional players 60-90 days",
      sheiAnnotation: "High inventory days + aging inventory = cash flow pressure + obsolescence cost",
      version: "1.0",
    },
    {
      kpiName: "On-Shelf Availability (%)",
      definition: "% of SKUs available on shelf when audited",
      functionTag: "SUPPLY_CHAIN",
      bestInClass: "92-97%",
      industryMedian: "84-91%",
      laggard: "<78%",
      indiaContext: "India general trade OSA often 75-85% due to last-mile gaps",
      sheiAnnotation: "OSA is where SC performance becomes revenue performance",
      version: "1.0",
    },
    {
      kpiName: "SC Cost as % of Revenue",
      definition: "Total supply chain cost / Revenue",
      functionTag: "SUPPLY_CHAIN",
      bestInClass: "6-9%",
      industryMedian: "10-14%",
      laggard: ">18%",
      indiaContext: "India: Distribution cost alone often 8-12%. SC cost is the lever most mid-tier Indian FMCG companies have not pulled",
      sheiAnnotation: "SC cost is the lever most mid-tier Indian FMCG companies have not pulled",
      version: "1.0",
    },
    {
      kpiName: "Perfect Order Rate (%)",
      definition: "Orders delivered complete, on-time, undamaged, correctly invoiced",
      functionTag: "SUPPLY_CHAIN",
      bestInClass: "92-97%",
      industryMedian: "82-90%",
      laggard: "<75%",
      indiaContext: "India: [Data gap — primary source needed]",
      sheiAnnotation: "Best proxy for overall SC reliability; single metric CXOs understand immediately",
      version: "1.0",
    },
    {
      kpiName: "EBITDA Margin (%)",
      definition: "EBITDA / Revenue",
      functionTag: "FINANCIAL",
      bestInClass: "22-28%",
      industryMedian: "15-20%",
      laggard: "<10%",
      indiaContext: "HUL ~23%; Dabur ~18%; Britannia ~16%",
      sheiAnnotation: "Input cost volatility and A&P reinvestment are the key drivers of variance",
      version: "1.0",
    },
    {
      kpiName: "Working Capital (Days)",
      definition: "Net working capital / (Revenue/365)",
      functionTag: "FINANCIAL",
      bestInClass: "Negative to 0",
      industryMedian: "15-30 days",
      laggard: ">45 days",
      indiaContext: "HUL runs negative WC; most India players 20-35 days",
      sheiAnnotation: "Best-in-class = distributors finance inventory; transformation opportunity for mid-tier players",
      version: "1.0",
    },
    {
      kpiName: "Trade Spend (% of Revenue)",
      definition: "Total trade promotions / Revenue",
      functionTag: "FINANCIAL",
      bestInClass: "8-12%",
      industryMedian: "14-18%",
      laggard: ">22%",
      indiaContext: "India mid-tier players often 18-22%; inefficient promo structures",
      sheiAnnotation: "High trade spend with low volume response = broken trade promotion optimization",
      version: "1.0",
    },
    {
      kpiName: "Numeric Distribution (%)",
      definition: "% of relevant outlets stocking the product",
      functionTag: "SALES_DISTRIBUTION",
      bestInClass: "85-95%",
      industryMedian: "65-80%",
      laggard: "<50%",
      indiaContext: "HUL flagship ~90%; regional brands often 40-60%",
      sheiAnnotation: "Numeric dist = reach; weighted dist = revenue-relevant reach",
      version: "1.0",
    },
    {
      kpiName: "E-commerce Channel Growth (%)",
      definition: "YoY revenue growth from online channels",
      functionTag: "SALES_DISTRIBUTION",
      bestInClass: "25-45%",
      industryMedian: "15-25%",
      laggard: "<10%",
      indiaContext: "India: Quick-commerce growing 40-60%; general e-comm 15-25%",
      sheiAnnotation: "Q-commerce now the real signal; track separately from Amazon/Flipkart",
      version: "1.0",
    },
  ]);

  await db.insert(playbookSectionsTable).values([
    {
      title: "Why Supply Chain is the FMCG Competitive Battlefield",
      functionTag: "SUPPLY_CHAIN",
      sectionNumber: 1,
      whyItMatters: "Supply chain is where FMCG companies win or lose — but most executives still treat it as a cost function rather than a competitive weapon. P&G's supply chain has been ranked #1 globally by Gartner for nine of the past twelve years. This is not coincidence: P&G's SC capability allows it to launch a new SKU in 40 countries simultaneously, respond to a demand spike within 72 hours, and run forecast accuracy above 85% in categories where competitors struggle to reach 65%. The FMCG companies that will win the next decade are not those with the best brands — they are those with the best supply chains.",
      industryLandscape: "FMCG supply chains are structurally harder than most manufacturing sectors for three compounding reasons.\n\nFirst, the SKU complexity is extreme — a company like HUL manages 2,000+ SKUs across dozens of categories. Each SKU has a different demand pattern, shelf life, production constraint, and distribution requirement. No single planning system handles this well without deliberate design.\n\nSecond, demand in FMCG is structurally promotional — between 15-25% of FMCG revenue flows through trade promotions, and promotions create artificial demand spikes that statistical forecasting models treat as signal rather than noise. The result is a consistent pattern of over-forecasting promo periods and under-preparing for non-promo demand, creating an inventory distortion cycle that costs the average FMCG company 2-4% of revenue annually.\n\nThird, the distribution model in India creates a unique last-mile complexity. Serving 12 million kirana stores through a chain of distributors, stockists, and field sales requires a planning and execution infrastructure fundamentally different from serving 50,000 supermarkets.",
      failureModes: "**Over-Reliance on Statistical Forecasting:** Time-series models built for stable channels fail catastrophically when applied to promotional spikes or quick-commerce patterns. Companies continue to optimize these models rather than replacing them.\n\n**Push Culture Without Pull Infrastructure:** Most India FMCG companies still operate a push model — producing to forecast, loading distributors. Without real-time sell-through visibility, the push model generates excess inventory at every tier.\n\n**SC as Cost Center Mindset:** When SC reports to Finance rather than as a strategic P&L-impacting function, investment decisions are made on cost reduction rather than revenue enablement.\n\n**Technology Before Process:** The most common failure mode is buying a world-class planning tool and running a 1990s S&OP process on top of it. Technology selection must follow process design.\n\n**Last-Mile Blindness:** Most FMCG companies can tell you what they shipped to distributors; few can tell you what actually sold at the shelf. The data gap makes the entire SC optimization exercise academic.",
      whatGoodLooksLike: "P&G's supply chain is the global benchmark. Key characteristics: demand-driven replenishment (pull, not push) across 180 markets; forecast accuracy above 85% at the category level; OTIF above 95% to retail customers; SC cost as a percentage of revenue below 8%. The enablers: 25 years of SAP investment, a proprietary demand sensing platform integrating POS data, social signals, and weather, and a SC organization treated as a strategic capability.\n\nFor India context, HUL is the domestic benchmark. Its RTM infrastructure (3,500+ redistribution stockists, DMS across the network, field sales app for real-time order capture) represents the current state of the art. The question for any Indian FMCG company is not whether to replicate HUL's model — it is which elements remain relevant as channels shift.",
      technologyEnablers: "**SAP IBP:** Most common in large FMCG; strong if SAP-heavy. Implementation complexity high; requires significant master data quality.\n\n**o9 Solutions:** Strong in FMCG; modern interface; better external signal integration than SAP IBP. Growing in India (Tata Consumer, some Unilever entities).\n\n**Kinaxis RapidResponse:** Best-in-class for scenario planning. Stronger in complex global SC; less common in India FMCG.\n\n**Beatroute/Bizom (DMS):** Leading Indian DMS platforms. Strong in general trade; mobile-first. Widely used in India FMCG mid-tier.",
      consultingEntryPoints: "**Trigger:** Client's OTIF is below 85% and leadership has no visibility into root cause.\n**Thoucentric Angle:** SC Diagnostic → KPI Baseline → Improvement Roadmap\n**Engagement Type:** Diagnostic\n\n**Trigger:** Client is evaluating S/4HANA or advanced planning tool investment.\n**Thoucentric Angle:** Technology selection advisory and business case development\n**Engagement Type:** Advisory\n\n**Trigger:** Client's demand plan accuracy is declining as digital channels grow.\n**Thoucentric Angle:** Demand Sensing Architecture Design\n**Engagement Type:** Transformation",
      status: "COMPLETE",
      version: "1.0",
    },
    {
      title: "KPI Framework and Diagnostic Benchmarks",
      functionTag: "SUPPLY_CHAIN",
      sectionNumber: 2,
      whyItMatters: "The most effective diagnostic opening is not a questionnaire — it is a benchmark conversation. Present the industry ranges, ask where the client sits, and watch the reaction. If the client does not know where they sit on more than 3 of these 9 metrics, that is itself a finding: the company lacks measurement infrastructure for SC performance management.",
      industryLandscape: "SC maturity distribution is wide: global leaders (P&G, Unilever, Nestlé) operate at a level Indian mid-tier players will take a decade to reach. Within India FMCG, the gap between HUL and mid-tier is large and widening — HUL's SC investment over the past five years (S/4HANA, demand planning transformation, DTR pilot) is creating a moat harder to cross with each passing year.\n\nKey patterns in Indian FMCG SC maturity: Mobile order-taking is universal (A-level maturity). DMS deployment is widespread but quality varies (D-A range). Advanced planning (IBP, o9, Kinaxis) is rare outside HUL and ITC. Demand sensing with external signals is essentially P&G-only territory in India.",
      failureModes: "**Tracking OTIF to Distributor Only:** The distribution gap — what happens between distributor and retailer — is where most India FMCG companies fly blind. Distributor OTIF of 88% can mask retailer OTIF of 72%.\n\n**Inventory Days Without Decomposition:** Company-level inventory days hide where the inventory is sitting. The problem is usually FG at CFA/depot level, not RM at plant — but without decomposition, it's invisible.\n\n**No Demand Forecast Bias Tracking:** Accuracy (MAPE) without bias is half the picture. Systematic over-forecasting in push-model companies generates excess inventory that never appears in the P&L until obsolescence.",
      whatGoodLooksLike: "A leading-practice organization tracks all 9 KPIs in this section in real-time with channel and category decomposition. Their S&OP meeting is a decision forum, not a reporting meeting. They have a single version of truth for demand and inventory, and the SC team has P&L accountability for cost-to-serve.",
      status: "COMPLETE",
      version: "1.0",
    },
    {
      title: "Technology Landscape: Planning and Distribution",
      functionTag: "SUPPLY_CHAIN",
      sectionNumber: 3,
      whyItMatters: "Technology selection is the third-most important SC decision after operating model and organizational structure — but it is often treated as the first. Buying a world-class planning tool and running a 1990s S&OP process on top of it is the most expensive mistake in FMCG SC transformation. The technology landscape briefing exists to help consultants navigate vendor conversations with clients and ground technology selection in genuine business requirements.",
      technologyEnablers: "**Demand Planning / S&OP:**\n- SAP IBP: Most common in large FMCG; strong SAP integration. Implementation complexity high.\n- o9 Solutions: Strong in FMCG; modern interface; better external signal integration. Growing in India.\n- Kinaxis RapidResponse: Best-in-class for scenario planning; stronger in complex global SC.\n- Blue Yonder: Strong in demand and fulfillment; some India FMCG deployments.\n\n**Distribution Technology (India-Specific):**\n- Beatroute: Leading Indian DMS; strong in general trade; mobile-first. Used by Marico, Godrej CP.\n- Bizom: Strong DMS + trade promotion management; data analytics differentiator.\n- Shotgun: Emerging; strong mobile UX; suited for mid-size FMCG.\n\n**WMS:**\n- SAP EWM: Enterprise grade; suited for large centralized DCs.\n- Manhattan Associates: Strong in FMCG; good for high-velocity ambient goods.\n- Infor WMS: Mid-market option; faster implementation.",
      consultingEntryPoints: "**Trigger:** Client is selecting a demand planning tool and evaluating multiple vendors.\n**Thoucentric Angle:** Technology selection advisory — requirements definition, vendor evaluation, business case\n**Engagement Type:** Advisory\n\n**Trigger:** Client has deployed a planning tool but is not realizing expected benefits.\n**Thoucentric Angle:** Value realization assessment — process gap analysis, adoption improvement, configuration optimization\n**Engagement Type:** Diagnostic + Transformation",
      status: "STARTER",
      version: "1.0",
    },
    {
      title: "IT Technology Stack Map: Indian FMCG",
      functionTag: "IT_TECHNOLOGY",
      sectionNumber: 1,
      whyItMatters: "The technology stack of a client company is the single best predictor of their SC transformation readiness. Companies running fragmented ERP landscapes (multiple regional ERPs, no integrated data layer) cannot deploy advanced planning, demand sensing, or GenAI — regardless of budget or intent. Understanding the technology landscape before an engagement design is not optional; it is the diagnostic lens through which every other recommendation is filtered.",
      industryLandscape: "Indian FMCG technology maturity follows a predictable hierarchy: Mobile order-taking (universal A-level); DMS (widespread D-A range); Core ERP (mostly SAP in large companies, fragmented in mid-tier); Advanced planning (rare); GenAI (deployed use cases extremely rare).\n\nGlobal leaders (P&G, Unilever, Nestlé) are 5-8 years ahead of the India average on planning and intelligence layers. India leaders (HUL, ITC) are actively investing but 2-4 years behind on GenAI and advanced analytics. Mid-tier India players (Marico, Dabur, Emami) have the widest gap — and the biggest consulting opportunity.",
      failureModes: "**ERP Fragmentation from M&A:** Companies formed through acquisition often run 3-5 ERPs across geographies and business units. This prevents integrated planning and makes any GenAI deployment impossible.\n\n**Data Lake Without Data Quality:** Companies building data lakes without investing in master data management are creating expensive noise repositories rather than intelligence infrastructure.\n\n**Tool Proliferation Without Integration:** Excel-based S&OP on top of SAP with a separate DMS and an unconnected analytics platform is a common failure mode — multiple tools, no single version of truth.\n\n**GenAI Pilots Without Foundation:** Running AI pilots on bad data produces confident wrong answers. The pilot succeeds on demo day and fails in production.",
      consultingEntryPoints: "**Trigger:** Client is planning a GenAI initiative but has no assessment of readiness.\n**Thoucentric Angle:** GenAI Readiness Assessment\n**Engagement Type:** Diagnostic\n\n**Trigger:** Client's ERP landscape is fragmented across geographies/divisions.\n**Thoucentric Angle:** ERP harmonization roadmap and data architecture design\n**Engagement Type:** Transformation",
      status: "COMPLETE",
      version: "1.0",
    },
    {
      title: "GenAI Use Case Catalog: FMCG",
      functionTag: "IT_TECHNOLOGY",
      sectionNumber: 2,
      whyItMatters: "GenAI's value in FMCG is not uniformly distributed — some use cases have high ROI and low implementation risk; others are technically impressive but operationally marginal. This catalog exists to give consultants a structured view of the use case landscape so they can help clients prioritize investment in high-value, implementable use cases rather than impressive pilots.",
      industryLandscape: "Current deployment patterns by tier:\n\n**Global Leaders (P&G, Unilever, Nestlé):** 10-50+ deployed use cases across demand sensing, procurement, R&D, marketing, and SC. Full data infrastructure prerequisite met.\n\n**India Leaders (HUL, ITC):** 3-10 deployed use cases; demand forecasting and consumer insights most common. Benefiting from parent company global infrastructure.\n\n**India Mid-Tier (Dabur, Marico, Godrej CP):** 0-3 pilots; mostly consumer insights and marketing. No deployed SC use cases. Data infrastructure gap is the binding constraint.",
      failureModes: "**Starting with High-Complexity Use Cases:** Companies beginning GenAI journeys with demand sensing or formulation AI fail because these require the most data infrastructure. Starting with document processing or summarization produces quick wins that fund the harder work.\n\n**Confusing Pilot Success with Production Readiness:** A GenAI pilot that works on curated data in a controlled environment is not production-ready. The gap between pilot and production is where most Indian FMCG GenAI initiatives stall.\n\n**No Change Management for AI Outputs:** Demand planners who don't trust AI-generated forecasts will override them consistently, eliminating the value entirely. Change management is not optional.",
      consultingEntryPoints: "**Trigger:** Client has GenAI budget but no structured use case prioritization.\n**Thoucentric Angle:** GenAI use case prioritization workshop → ROI-ranked implementation roadmap\n**Engagement Type:** Advisory\n\n**Trigger:** Client's GenAI pilot is not scaling to production.\n**Thoucentric Angle:** Production readiness assessment — data quality, integration architecture, change management\n**Engagement Type:** Diagnostic + Advisory",
      status: "STARTER",
      version: "1.0",
    },
  ]);
}
