import { db } from "@workspace/db";
import {
  companiesTable,
  sheiCardsTable,
  signalsTable,
  benchmarksTable,
  playbookSectionsTable,
} from "@workspace/db";

export async function seedDatabase(force = false) {
  const existingCompanies = await db.select().from(companiesTable);
  if (existingCompanies.length >= 15 && !force) return;

  // Clear all existing data
  await db.delete(signalsTable);
  await db.delete(sheiCardsTable);
  await db.delete(benchmarksTable);
  await db.delete(playbookSectionsTable);
  await db.delete(companiesTable);

  // ─── COMPANIES ────────────────────────────────────────────────────────────
  await db.insert(companiesTable).values([
    {
      name: "HUL",
      fullName: "Hindustan Unilever Limited",
      tier: 1,
      geography: "INDIA",
      exchange: "BSE/NSE",
      irPage: "hul.co.in/investors",
      earningsCadence: "Quarterly",
      revenue: "₹62,756 Cr (FY24)",
      revenueGrowth: "~2-3% YoY",
      ebitdaMargin: "~23.4%",
      marketCap: "~₹5.5 lakh Cr",
      categories: "Home Care, Beauty & Personal Care, Foods & Refreshment",
      strategicPriorities: "Premiumization, RTM reinvention for quick-commerce, sustainability-linked SC",
      scIntelligence: "SAP S/4HANA migration in progress. ~40 factories. 3,500 redistribution stockists. DTR pilot in urban markets. Working capital under pressure from modern trade payment terms.",
      techIntelligence: "SAP S/4HANA migration. Piloted AI demand forecasting. E-commerce ~15-16% revenue. Quick-commerce growing 40%+ YoY.",
      openProblems: "RTM model redundancy for quick-commerce era. Demand forecasting degradation in digital-heavy categories. Horlicks SC integration incomplete.",
      quickTake: "HUL is the sector's most important real-time case study on distribution reinvention. Quick-commerce readiness and RTM transformation are the critical execution tests for FY26.",
      confidence: "HIGH",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "ITC",
      fullName: "ITC Limited (FMCG)",
      tier: 1,
      geography: "INDIA",
      exchange: "BSE/NSE",
      irPage: "itcportal.com/investor-zone",
      earningsCadence: "Quarterly",
      revenue: "₹73,929 Cr (FY24 total); FMCG ~₹20,000 Cr",
      revenueGrowth: "7-8% (FMCG segment)",
      ebitdaMargin: "~58% gross margin (Foods div)",
      marketCap: "~₹5.6 lakh Cr",
      categories: "Aashirvaad, Sunfeast, Yippee, Fiama, Vivel, Agri-business",
      strategicPriorities: "FMCG scale-up to ₹1 lakh Cr, agri-backward integration via e-Choupal (6,500 kiosks), premium portfolio extension",
      scIntelligence: "e-Choupal backward integration for agri-sourcing: 40,000 villages, 6,500 kiosks. DMS deployed. S/4HANA migration in progress. 70+ factories.",
      techIntelligence: "SAP S/4HANA migration underway. DMS across distributor network. GenAI nascent—limited SC deployments. Strong agri-procurement tech edge.",
      openProblems: "Modern trade execution quality gap. SC technology fragmentation vs. FMCG scale ambition. S/4HANA migration critical path.",
      quickTake: "ITC's FMCG segment is the most credible challenger to HUL—uniquely backed by e-Choupal agri integration no other player can replicate. SC technology catch-up is the bottleneck to next-phase growth.",
      confidence: "HIGH",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "Nestlé India",
      fullName: "Nestlé India Limited",
      tier: 1,
      geography: "INDIA",
      exchange: "NSE",
      irPage: "nestle.in/investors",
      earningsCadence: "Quarterly",
      revenue: "₹17,519 Cr (FY24)",
      revenueGrowth: "~8.8% YoY",
      ebitdaMargin: "~24.1%",
      marketCap: "~₹2.2 lakh Cr",
      categories: "Maggi, Nescafé, KitKat, Munch, Nestea, Milkmaid",
      strategicPriorities: "Out-of-Home channel expansion, premiumization, direct distribution deepening in rural Bharat",
      scIntelligence: "SAP IBP deployed for demand planning. Distribution: 8.6M outlets across India. Cold chain capability limited. Lean portfolio aids forecast accuracy.",
      techIntelligence: "SAP IBP for supply planning. AI in procurement for supplier risk. Strong ERP maturity vs. India mid-tier peers.",
      openProblems: "Rural penetration vs. category potential gap. Cold chain limitation for dairy/ice cream expansion. Trade promotion efficiency below peer benchmark.",
      quickTake: "Nestlé India's concentrated portfolio gives it forecast accuracy most peers envy. The rural whitespace opportunity is large but requires cold-chain investment HQ has been slow to commit.",
      confidence: "HIGH",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "Dabur",
      fullName: "Dabur India Limited",
      tier: 1,
      geography: "INDIA",
      exchange: "BSE/NSE",
      irPage: "dabur.com/investors",
      earningsCadence: "Quarterly",
      revenue: "₹12,404 Cr (FY24)",
      revenueGrowth: "~6.9% YoY",
      ebitdaMargin: "~18.8%",
      marketCap: "~₹85,000 Cr",
      categories: "Chyawanprash, Hajmola, Vatika, Real juices, Oral B, Dabur Red",
      strategicPriorities: "Naturals/Ayurvedic premium positioning, international expansion (Middle East/Africa/SE Asia), rural recovery",
      scIntelligence: "Fragmented ERP landscape (multiple regional ERPs, S/4HANA migration pending). Over-forecasting in seasonal categories. DMS capability lagging modern trade peers.",
      techIntelligence: "ERP fragmented. AI/ML mentioned in FY24 annual report for consumer insights. No confirmed SC AI deployments. GenAI readiness gap is a quantified consulting entry point.",
      openProblems: "GenAI announcement trap—board mandate, no deployed use cases. SC technology debt preventing integrated planning. International SC complexity growing.",
      quickTake: "Dabur is the textbook case of the India FMCG mid-tier challenge: strong heritage brands but technology and SC infrastructure not keeping pace. The 3-year window to close the GenAI gap is narrowing.",
      confidence: "MEDIUM",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "Marico",
      fullName: "Marico Limited",
      tier: 1,
      geography: "INDIA",
      exchange: "BSE/NSE",
      irPage: "maricoindia.com/investor-relations",
      earningsCadence: "Quarterly",
      revenue: "₹9,653 Cr (FY24)",
      revenueGrowth: "~7.2% YoY",
      ebitdaMargin: "~18.3%",
      marketCap: "~₹65,000 Cr",
      categories: "Parachute (coconut oil), Saffola (healthy foods/oils), Hair & Care, Set Wet, True Elements",
      strategicPriorities: "Saffola diversification into healthy snacking, D2C brand building (True Elements, Beardo), international markets (Bangladesh, Vietnam, Middle East)",
      scIntelligence: "MTCP mobile app for field sales deployed. Parachute demand highly seasonal—forecasting failures documented in FY24. D2C brands on separate SC infra. Advanced planning AI not evident.",
      techIntelligence: "DMS deployed (MTCP). CTO references digital transformation. No SC AI use cases. Separate D2C tech stack creating integration complexity.",
      openProblems: "Parachute demand forecasting in seasonal/commodity categories. D2C SC integration with core FMCG. Rural demand miss quantified in FY24 results.",
      quickTake: "Marico's transformation from Parachute-dependency is well underway but D2C SC complexity is growing faster than integration capability. The forecasting gap in core coconut oil is a quantified, immediate entry point.",
      confidence: "MEDIUM",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "Godrej CP",
      fullName: "Godrej Consumer Products",
      tier: 1,
      geography: "INDIA",
      exchange: "BSE/NSE",
      irPage: "godrejcp.com/investors",
      earningsCadence: "Quarterly",
      revenue: "₹14,864 Cr (FY24)",
      revenueGrowth: "~9.1% YoY",
      ebitdaMargin: "~20.8%",
      marketCap: "~₹95,000 Cr",
      categories: "HIT, Good Knight, Godrej No. 1, Expert (hair colour), Cinthol, Air Fresheners",
      strategicPriorities: "India rural penetration (target 50% rural revenue), Africa expansion (20%+ revenue), new product pipeline in home care",
      scIntelligence: "~1,300 distributors. DMS deployed across India network. Multi-geography SC: India, Indonesia, Africa with limited integration. Rural last-mile cost-to-serve economics challenging.",
      techIntelligence: "GenAI reference in investor day for marketing optimisation. SC AI not confirmed. Technology modernisation is priority gap.",
      openProblems: "Africa SC complexity with separate systems. Rural last-mile cost economics. Cross-geography integration lagging revenue growth.",
      quickTake: "Godrej CP's Africa story is underappreciated. The SC complexity from multi-geography operations with limited tech integration is the clearest consulting entry point.",
      confidence: "MEDIUM",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "Britannia",
      fullName: "Britannia Industries Limited",
      tier: 1,
      geography: "INDIA",
      exchange: "BSE/NSE",
      irPage: "britannia.co.in/investors",
      earningsCadence: "Quarterly",
      revenue: "₹16,480 Cr (FY24)",
      revenueGrowth: "~3.2% YoY",
      ebitdaMargin: "~17.8%",
      marketCap: "~₹1.1 lakh Cr",
      categories: "Biscuits (Good Day, Marie Gold, NutriChoice, Tiger), Dairy, Bread",
      strategicPriorities: "International expansion (50+ countries), dairy portfolio expansion, adjacencies in snacking and cake",
      scIntelligence: "43 own + 64 contract manufacturing units. Strong GT distribution. Dairy cold chain limited. Wheat and sugar commodity procurement is primary cost lever.",
      techIntelligence: "SAP-based ERP. DMS deployed. Commodity procurement hedging using market intelligence tools. No confirmed AI SC deployments.",
      openProblems: "Commodity cost inflation pass-through strategy. Dairy SC cold chain investment decision. International SC complexity management.",
      quickTake: "Britannia's procurement economics are tightly tied to wheat and sugar commodity cycles. The international ambition is real but requires SC architecture upgrade. Commodity hedging sophistication is a procurement consulting entry point.",
      confidence: "MEDIUM",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "Emami",
      fullName: "Emami Limited",
      tier: 1,
      geography: "INDIA",
      exchange: "BSE/NSE",
      irPage: "emamiltd.in/investor-relations",
      earningsCadence: "Quarterly",
      revenue: "₹3,762 Cr (FY24)",
      revenueGrowth: "~10.3% YoY",
      ebitdaMargin: "~26.6%",
      marketCap: "~₹18,000 Cr",
      categories: "BoroPlus, Fair & Handsome, Navratna, Zandu, Kesh King, Dermicool",
      strategicPriorities: "Digital-first portfolio (BoroPlus D2C), Zandu health science expansion, international (MENA, Africa)",
      scIntelligence: "Seasonally intense portfolio (winter: BoroPlus; summer: cooling oils). Demand forecasting for seasonal spikes historically problematic. 19 own factories.",
      techIntelligence: "ERP in place. DMS deployed. Digital push in marketing. SC AI not confirmed.",
      openProblems: "Seasonal demand volatility management. D2C SC integration. International SC standardisation.",
      quickTake: "Emami's high seasonality creates recurrent forecasting and inventory challenges that are a strong consulting entry point. The EBITDA margin at 26%+ is the sector's highest—premium cost-to-serve model at risk from channel proliferation.",
      confidence: "MEDIUM",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "Tata Consumer",
      fullName: "Tata Consumer Products Limited",
      tier: 1,
      geography: "INDIA",
      exchange: "BSE/NSE",
      irPage: "tataconsumer.com/investors",
      earningsCadence: "Quarterly",
      revenue: "₹15,206 Cr (FY24)",
      revenueGrowth: "~8.4% YoY",
      ebitdaMargin: "~15.2%",
      marketCap: "~₹1.0 lakh Cr",
      categories: "Tata Salt, Tata Tea, Himalayan water, Tetley, Eight O'Clock Coffee, Starbucks (JV)",
      strategicPriorities: "Merger integration (Tata Foods + Tata Beverages), portfolio expansion into health & nutrition, Starbucks India scale-up",
      scIntelligence: "Complex SC post-merger integration. Tea procurement from Assam/Darjeeling + global. Salt manufacturing at Mithapur. Global Tetley SC integration ongoing.",
      techIntelligence: "Post-merger ERP harmonisation in progress. Global Tetley/Eight O'Clock systems being integrated with India entity.",
      openProblems: "Post-merger SC integration complexity. ERP harmonisation timeline. International sourcing procurement optimisation.",
      quickTake: "Tata Consumer is mid-transformation from a commodities-led portfolio to a premium consumer company. Post-merger SC integration is a multi-year programme—the consulting opportunity is in the integration architecture and procurement redesign.",
      confidence: "MEDIUM",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "Colgate India",
      fullName: "Colgate-Palmolive (India) Limited",
      tier: 1,
      geography: "INDIA",
      exchange: "BSE/NSE",
      irPage: "colgateinvestors.com",
      earningsCadence: "Quarterly",
      revenue: "₹5,748 Cr (FY24)",
      revenueGrowth: "~9.1% YoY",
      ebitdaMargin: "~31.8%",
      marketCap: "~₹65,000 Cr",
      categories: "Colgate (toothpaste, brushes), Palmolive",
      strategicPriorities: "Premiumisation in oral care (Electric toothbrush, premium pastes), naturals positioning vs. Patanjali/Dabur",
      scIntelligence: "Lean 3-factory network. High procurement dependency on imported raw materials (e.g., fluoride, fragrance). Strong GT and modern trade distribution.",
      techIntelligence: "Colgate-Palmolive global SAP deployment. Advanced trade promotion management tools. AI demand sensing via global parent platform.",
      openProblems: "Import cost exposure for key inputs. Distribution depth vs. Dabur Red and Patanjali in rural. Premium portfolio velocity in modern trade.",
      quickTake: "Colgate India has the sector's best EBITDA margin at 31%+ but faces structural competitive pressure from naturals/Ayurvedic entrants. Procurement cost management for imported inputs is the clearest SC lever.",
      confidence: "HIGH",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "Unilever",
      fullName: "Unilever PLC",
      tier: 1,
      geography: "GLOBAL",
      exchange: "LSE/NYSE",
      irPage: "investors.unilever.com",
      earningsCadence: "Quarterly",
      revenue: "€59.6B (FY24)",
      revenueGrowth: "~4.2% underlying sales growth",
      ebitdaMargin: "~18.1%",
      marketCap: "~£38B",
      categories: "Beauty & Wellbeing, Personal Care, Home Care, Nutrition, Ice Cream (separating)",
      strategicPriorities: "Ice Cream separation (€7.9B business), Power Brands focus (30 brands = 75% revenue), €800M cost-saving productivity programme",
      scIntelligence: "300+ manufacturing sites globally. Demand sensing model required 'significant recalibration' post-2023. AI-powered demand sensing platform with external signal integration. CSCO-led transformation programme.",
      techIntelligence: "SAP S/4HANA fully deployed globally. Google Cloud and Azure for data. AI demand sensing with POS, social, weather integration.",
      openProblems: "Ice Cream SC separation complexity. Demand sensing recalibration across multiple markets. Channel proliferation planning model gaps.",
      quickTake: "Unilever's demand sensing programme is 3-5 years ahead of India market—the gap is the consulting opportunity for every India FMCG engagement. Ice Cream separation is the sector's biggest SC design challenge of 2025.",
      confidence: "HIGH",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "P&G",
      fullName: "Procter & Gamble",
      tier: 1,
      geography: "GLOBAL",
      exchange: "NYSE",
      irPage: "pginvestor.com",
      earningsCadence: "Quarterly",
      revenue: "$84.0B (FY24)",
      revenueGrowth: "~3.1% organic",
      ebitdaMargin: "~24.8%",
      marketCap: "~$380B",
      categories: "Beauty, Grooming, Health Care, Fabric & Home Care, Baby/Feminine/Family Care",
      strategicPriorities: "Innovation-led premium growth, Superiority programme (product/packaging/execution), ongoing Productivity programme",
      scIntelligence: "Gartner SC Top 25: #1 for 9 of 12 years. Proprietary demand sensing with POS + social + weather. OTIF >95%. Forecast accuracy >85% at category level.",
      techIntelligence: "SAP globally deployed. 50+ GenAI use cases deployed (FY24). Google Cloud for demand sensing. AI in trade promotion optimisation and manufacturing.",
      openProblems: "Emerging market SC complexity as channels fragment (India, SE Asia). Channel proliferation risk acknowledged despite high OTIF.",
      quickTake: "P&G is the global SC benchmark—5-8 years ahead of India mid-tier. Every diagnostic with an Indian FMCG client should reference P&G's OTIF and forecast accuracy benchmarks to quantify the gap.",
      confidence: "HIGH",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "Nestlé Global",
      fullName: "Nestlé S.A.",
      tier: 1,
      geography: "GLOBAL",
      exchange: "SIX Swiss Exchange",
      irPage: "nestle.com/investors",
      earningsCadence: "Quarterly",
      revenue: "CHF 91.4B (FY24)",
      revenueGrowth: "~2.2% organic (decelerating)",
      ebitdaMargin: "~17.4%",
      marketCap: "~CHF 220B",
      categories: "Powdered Beverages, PetCare (Purina), Health Science, Prepared Dishes, Confectionery, Dairy",
      strategicPriorities: "Portfolio reshaping (divest underperforming brands), volume-led growth pivot post-pricing, CHF 2.5B savings under new CEO Laurent Freixe",
      scIntelligence: "449 factories globally. SAP IBP for demand planning. AI in procurement for supplier risk. Product concentration gives superior forecast accuracy vs. high-SKU peers.",
      techIntelligence: "SAP globally. AI in procurement (supplier risk), SC (demand sensing), R&D (formulation). Strong technology maturity.",
      openProblems: "Price-volume rebalancing after 2 years of price increases. Portfolio simplification execution risk. India distribution depth gaps.",
      quickTake: "Nestlé's stable forecast accuracy (vs. peers struggling) is a counterintuitive benchmark: it comes from SKU concentration, not technology. Useful data point in SC diagnostic conversations about portfolio complexity.",
      confidence: "HIGH",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "Reckitt India",
      fullName: "Reckitt Benckiser (India) Ltd",
      tier: 1,
      geography: "INDIA",
      exchange: "BSE",
      irPage: "reckitt.com/investors",
      earningsCadence: "Quarterly",
      revenue: "₹5,200 Cr est. (FY24)",
      revenueGrowth: "~5-7% YoY",
      ebitdaMargin: "~22-24%",
      marketCap: "~₹55,000 Cr",
      categories: "Dettol, Harpic, Strepsils, Durex, Veet, Mortein",
      strategicPriorities: "Hygiene and health category premiumisation post-COVID, Dettol brand extension, modern trade and e-commerce execution",
      scIntelligence: "Import-heavy procurement for several product categories. Clean, lean SKU portfolio aids demand planning. Modern trade execution quality is strong.",
      techIntelligence: "Global Reckitt SAP deployment. Advanced e-commerce analytics. Demand planning linked to global platform.",
      openProblems: "Input cost exposure from import dependency. Rural distribution depth vs. HUL/ITC. Category relevance in hygiene post-COVID normalisation.",
      quickTake: "Reckitt India's strength post-COVID has been the Dettol brand halo. The procurement risk from import dependency and rural distribution gaps are the two quantifiable consulting entry points.",
      confidence: "MEDIUM",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
    {
      name: "Mondelez India",
      fullName: "Mondelez International (India)",
      tier: 1,
      geography: "INDIA",
      exchange: "NASDAQ (parent)",
      irPage: "mondelezinternational.com/investors",
      earningsCadence: "Quarterly",
      revenue: "₹4,500 Cr est. (FY24)",
      revenueGrowth: "~8-10% YoY",
      ebitdaMargin: "~18-20%",
      marketCap: "~$28B (parent)",
      categories: "Cadbury (Dairy Milk, Bournvita, 5Star, Gems), Oreo, Toblerone",
      strategicPriorities: "Cocoa procurement security (global cocoa price crisis), premiumisation in gifting and sharing formats, modern trade and quick-commerce execution",
      scIntelligence: "Global cocoa procurement crisis (prices 3x in 2024). Chocolate manufacturing at Sri City, Hyderabad. Distribution deepening for impulse snacking.",
      techIntelligence: "Global Mondelez SAP. Demand sensing linked to parent platform. Cocoa futures and commodity hedging programmes.",
      openProblems: "Cocoa cost crisis—global cocoa prices tripled in 2024, directly impacting margins. Gifting SC complexity during Diwali/festival season. Premium price point resistance.",
      quickTake: "Mondelez India's cocoa procurement crisis is the most pressing supply chain challenge in FMCG right now. Commodity cost management and alternative sourcing strategy is an immediate, quantifiable consulting opportunity.",
      confidence: "MEDIUM",
      version: "1.0",
      nextRefresh: "2025-07-01",
    },
  ]);

  // ─── SHEI CARDS ───────────────────────────────────────────────────────────
  await db.insert(sheiCardsTable).values([
    {
      cardId: "SHEI-2025-Q2-01",
      title: "Demand Forecasting Architecture Collapse in Quick-Commerce FMCG",
      functionTag: "SUPPLY_CHAIN",
      geographyTag: "BOTH",
      urgency: "IMMEDIATE",
      status: "ACTIVE",
      signal: "FMCG companies globally report growing inventory distortion despite planning technology investments. HUL Q3 FY25 management noted quick-commerce demand patterns are 'fundamentally different' from GT. Unilever acknowledged demand sensing models required 'significant recalibration' post-2023. Marico reported over-forecasting in Parachute with inventory days uptick FY24.",
      hypothesis: "Traditional statistical demand forecasting—built for weekly general trade replenishment—is structurally incompatible with 4-hour quick-commerce fulfillment rhythms and viral social-media demand spikes. FMCG companies that do not rebuild their demand sensing architecture will see forecast accuracy degrade 10-15 percentage points as modern channels grow to 25-40% of revenue by FY27.",
      evidence: "HUL: Digital channels 15-16% of revenue; quick-commerce growing 40%+ YoY. Aging inventory in Foods segment disclosed. Marico: Over-forecasting in Parachute coconut oil—inventory days up 6 days YoY in FY24. Unilever Global: Demand sensing recalibration acknowledged; accuracy below 75% at category level in some markets. P&G: OTIF 94%+ but channel proliferation risk flagged. Counter: Nestlé's stable accuracy attributed to portfolio concentration (fewer SKUs).",
      clientImplication: "CPOs and CSCOs face a fundamental architecture decision: optimise existing time-series forecasting engine (diminishing returns) or invest in a demand sensing layer integrating external signals in near-real-time. Window for this decision is 12-18 months before modern-channel growth makes current architecture untenable.",
      thoucentriqAngle: "Phase 1: Demand Sensing Diagnostic (4-6 weeks)—forecast accuracy by channel/SKU/region, quantify revenue leakage and inventory cost. Phase 2: Architecture Design—sensing model selection, technology (o9, Kinaxis, SAP IBP), data sourcing strategy. Phase 3: Implementation Advisory—sensing layer build, S&OP cadence change management.",
      financialImpact: "For a ₹5,000 Cr revenue FMCG company: 1% forecast accuracy improvement = ~₹25 Cr inventory cost reduction + ~₹40 Cr revenue recovery from reduced stockouts. HUL estimated inventory distortion cost: ₹300-500 Cr annually. Industry: 3-4% of COGS locked in excess inventory for mid-tier India FMCG.",
      whyNow: "Quick-commerce crossed 15% of HUL's revenue in Q3 FY25 and is growing 40%+ YoY. FY26 planning cycles are being set NOW. Companies that wait 12 months will face compounding problems: declining OTIF, rising inventory costs, and lost shelf space in modern trade.",
      relatedCompanies: "HUL,Marico,Unilever,P&G,Godrej CP",
      pitchAnchor: "We tracked a consistent pattern across seven FMCG companies this quarter: demand forecast accuracy is declining despite technology investment, and the common thread is quick-commerce. HUL's planning team is using a monthly forecast model to manage a 4-hour fulfillment channel—and they are not alone.",
      provocQuestion: "If quick-commerce reaches 30% of your revenue in three years, how much inventory buffer are you carrying today that you won't be able to afford then?",
      version: "1.0",
      nextReview: "2025-07-01",
    },
    {
      cardId: "SHEI-2025-Q2-02",
      title: "Cocoa Procurement Crisis: FMCG Confectionery Cost Shock",
      functionTag: "PROCUREMENT",
      geographyTag: "GLOBAL",
      urgency: "IMMEDIATE",
      status: "ACTIVE",
      signal: "Global cocoa prices tripled in 2024—from ~$2,600/ton to over $10,000/ton—driven by climate failures in Ghana and Ivory Coast (70% of global supply). Mondelez, Nestlé, Mars, and Lindt all disclosed material margin pressure. Mondelez Q4 FY24 earnings: gross margin down 280bps YoY directly attributed to cocoa. Cadbury products in India face Rs 5-15 price increases across SKUs.",
      hypothesis: "The cocoa price crisis is not a temporary spike—it reflects structural supply fragility in West Africa (aging cocoa trees, farmer income economics, climate disruption) compounded by speculative futures positioning. FMCG confectionery companies that have not diversified cocoa sourcing, invested in alternative ingredients, or restructured procurement contracts will face sustained margin compression of 200-400bps through FY26.",
      evidence: "Ghana/Ivory Coast crop: FY24 ~3.8M tons vs. historical 4.5M ton average; FY25 outlook negative. Cocoa futures ICE: $10,400/ton (April 2025) vs. $2,600 (Jan 2024). Mondelez gross margin: 37.3% (FY24) vs. 40.1% (FY23). Mars: announced Snickers bar downsizing ('shrinkflation') in EU/UK. Nestlé: Investing in cocoa farming support in Ivory Coast. Barry Callebaut (largest chocolate B2B supplier): issued profit warning Q2 FY24.",
      clientImplication: "Confectionery procurement leaders need immediate action on three fronts: (1) contract renegotiation with forward pricing for 18-24 months, (2) alternative ingredient research (carob, chicory, non-cocoa compound), (3) recipe optimisation to reduce cocoa per unit without taste compromise. The companies executing on all three will protect margins; those waiting will compress.",
      thoucentriqAngle: "Procurement Resilience Assessment for confectionery clients: map cocoa exposure by SKU and contract type, quantify margin impact, design diversification roadmap. Engagement scope: 6-8 weeks diagnostic, followed by sourcing strategy redesign and supplier negotiation support.",
      financialImpact: "Mondelez India estimated impact: ₹200-300 Cr EBIT risk at current cocoa prices. Industry-wide India confectionery EBIT impact: ~₹800 Cr annually at $10,000/ton cocoa vs. historical pricing. Every 10% cocoa price reduction = ~₹50 Cr savings for a mid-size India confectionery player.",
      whyNow: "FY25-26 annual procurement contracts are being finalised. This is the last window to lock in forward pricing before FY26 cocoa exposure becomes unhedgeable at current prices. Companies acting now will have 200-300bps EBIT advantage vs. late movers.",
      relatedCompanies: "Mondelez India,Nestlé India,Nestlé Global,Britannia",
      pitchAnchor: "Cocoa at $10,000/ton is a 3x step-change from two years ago. Mondelez's gross margin has already dropped 280bps. We have a procurement resilience framework specifically for commodity-exposed FMCG that maps your exposure and designs the hedging and diversification response.",
      provocQuestion: "What percentage of your confectionery COGS is exposed to cocoa price risk with no contractual protection beyond 6 months?",
      version: "1.0",
      nextReview: "2025-07-01",
    },
    {
      cardId: "SHEI-2025-Q2-03",
      title: "India FMCG Procurement Maturity Gap: Strategic vs. Transactional",
      functionTag: "PROCUREMENT",
      geographyTag: "INDIA",
      urgency: "MEDIUM_TERM",
      status: "ACTIVE",
      signal: "Procurement function in India FMCG companies operates predominantly as a transactional cost centre—focused on vendor negotiation and purchase order execution—rather than as a strategic business partner. Annual reports of Dabur, Marico, Emami, and Godrej CP do not mention procurement transformation in strategic priorities. In contrast, global benchmarks (P&G, Unilever) now treat procurement as a value-creation function with technology and analytics investment at parity with SC operations.",
      hypothesis: "Indian FMCG mid-tier companies leave 2-4% of COGS savings unrealised annually due to procurement immaturity: absence of category management, demand aggregation, supplier development, and analytics-driven sourcing. As commodity volatility increases (post-cocoa/palm oil shocks) and input complexity grows (sustainable packaging mandates), the gap between transactional and strategic procurement will widen from a cost issue to a structural competitiveness threat.",
      evidence: "P&G: Procurement function generates $2B+ in COGS savings annually through category management and supplier innovation partnerships. Unilever: Responsible Sourcing programme directly links procurement to sustainability targets—ESG-driven supplier qualification now a cost and licence-to-operate lever. India mid-tier: Dabur FY24 annual report: zero mentions of procurement transformation. Marico: 'cost efficiency' mentioned but no category management structure referenced. Gartner: Top-quartile procurement maturity in FMCG reduces COGS by 3-5% vs. bottom-quartile.",
      clientImplication: "CFOs and CPOs in India FMCG should challenge procurement transformation as a top-3 EBIT lever. A structured transition from transactional to strategic procurement—with category management, demand aggregation, supplier scorecards, and technology—can generate 2-4% COGS improvement within 24 months with 5-8x ROI on consulting investment.",
      thoucentriqAngle: "Procurement Maturity Assessment (3-week diagnostic): current state mapping against Gartner 5-level maturity model, gap quantification, and roadmap design. Followed by Category Management Transformation: structured categories (packaging, ingredients, indirect), supplier negotiation playbook, technology selection.",
      financialImpact: "India mid-tier FMCG (₹5,000-15,000 Cr revenue): 2-4% COGS savings = ₹100-600 Cr EBIT improvement. Payback on procurement transformation investment: 6-12 months. Benchmark: P&G achieves 3.1% procurement savings as % of COGS annually vs. India FMCG average of ~0.8%.",
      whyNow: "Three converging pressures make FY25-26 the inflection point: (1) post-inflation commodity normalisation creates a window to lock in savings before next spike, (2) SEBI sustainability reporting mandates require supplier transparency procurement functions cannot currently provide, (3) quick-commerce demand volatility is making procurement planning rhythms incompatible with sales patterns.",
      relatedCompanies: "Dabur,Marico,Emami,Britannia,Godrej CP",
      provocQuestion: "What percentage of your COGS is actively managed through category strategies with quarterly supplier scorecards and structured negotiation cycles?",
      version: "1.0",
      nextReview: "2025-08-01",
    },
    {
      cardId: "SHEI-2025-Q2-04",
      title: "Sustainable Packaging Mandate: SC & Procurement Transformation Trigger",
      functionTag: "SUPPLY_CHAIN",
      geographyTag: "BOTH",
      urgency: "MEDIUM_TERM",
      status: "ACTIVE",
      signal: "India's Plastic Waste Management Rules 2022 enforcement is tightening—EPR (Extended Producer Responsibility) compliance is now actively monitored and fines being levied. EU's CSRD mandates scope 3 emissions disclosure for Indian subsidiaries of global FMCG by 2025. Global FMCG companies (Unilever, P&G, Nestlé) have committed to 100% recyclable/reusable packaging by 2025-2030 with material compliance gaps reported. Industry: 30% of India FMCG packaging is multi-layer plastics with no current recyclable substitute at commercial scale.",
      hypothesis: "Sustainable packaging transition is being managed as a compliance and marketing exercise rather than a supply chain redesign programme. Companies that fail to integrate packaging sustainability into procurement strategy, supplier development, and SC design will face three simultaneous risks by FY27: regulatory fines, rising packaging cost from EPR levies, and customer delisting risk from modern trade and global retail chains demanding sustainability credentials.",
      evidence: "India EPR levies: ₹20-50/kg on non-recyclable plastic packaging, effective FY24. Unilever India: 82% recyclable packaging as of 2024; target 100% by 2025—on track to miss. P&G global: 65% recyclable primary packaging; committed $1B to sustainable packaging innovation. HUL: 99% virgin plastic reduction target by 2030; FY24 progress at 43%. Britannia: Multi-layer biscuit packaging with no cost-viable recyclable alternative at current scale. SEBI BRSR: Mandatory scope 1/2 reporting; Scope 3 (packaging value chain) required from FY25 for top 1,000 listed companies.",
      clientImplication: "Procurement and SC leaders need to treat packaging sustainability as a material EBIT risk, not a CSR initiative: (1) EPR cost trajectory modelling for current packaging mix, (2) supplier development for recyclable alternatives, (3) SC redesign for packaging collection/reverse logistics, (4) BRSR compliance data infrastructure build.",
      thoucentriqAngle: "Sustainable Packaging SC Assessment: SKU-level mapping of packaging materials and EPR liability, supplier capability assessment for sustainable alternatives, SC redesign for reverse logistics. Typically a 8-12 week engagement with ₹50-200 Cr EBIT risk quantification as the output.",
      financialImpact: "HUL estimated EPR liability: ₹150-300 Cr annually at current packaging mix if full enforcement applies. Industry-wide India FMCG EPR liability at 100% enforcement: ~₹2,500 Cr/year. Offset: Recyclable packaging cost premium is 15-25% currently but declining—companies that move early lock in lower transition costs.",
      whyNow: "MoEFCC enforcement of EPR is shifting from warnings to fines in FY25. SEBI BRSR Scope 3 disclosures are due for top-1000 listed companies from FY25. The compliance window is closing—companies acting on SC redesign in FY25 will be 2 years ahead of laggards.",
      relatedCompanies: "HUL,Unilever,P&G,Nestlé India,Britannia,Marico",
      provocQuestion: "Have you modelled the EBIT impact if EPR levies apply to 100% of your current non-recyclable packaging mix?",
      version: "1.0",
      nextReview: "2025-09-01",
    },
    {
      cardId: "SHEI-2025-Q2-05",
      title: "GenAI SC Deployment Gap: India FMCG vs. Global Benchmark",
      functionTag: "IT_TECHNOLOGY",
      geographyTag: "INDIA",
      urgency: "MEDIUM_TERM",
      status: "ACTIVE",
      signal: "India FMCG mid-tier companies (Dabur, Marico, Emami, Godrej CP) are announcing GenAI exploration initiatives in annual reports and investor calls, but concrete deployed SC use cases with measurable outcomes are rare. Global peers P&G (50+ GenAI use cases), Unilever (AI demand sensing), and Nestlé (AI in procurement and R&D) are 2-3 years ahead. The gap is not ambition—virtually every India FMCG CXO has a GenAI task force. The gap is foundational: clean data, process standardisation, and integrated ERP landscapes.",
      hypothesis: "India FMCG companies are in a GenAI 'announcement trap'—publicly committing to AI transformation while privately lacking data and process infrastructure prerequisites. Without addressing data quality, ERP fragmentation, and SC process standardisation, GenAI pilots will remain pilots. This creates an 18-24 month implementation crisis as leadership pressure for GenAI ROI intensifies while foundation gaps remain unaddressed.",
      evidence: "P&G FY24: 50+ GenAI use cases deployed (demand sensing, trade promo, manufacturing). Unilever: AI demand sensing with social/POS/weather signals. HUL: Piloted AI demand forecasting; quick-commerce planning gaps persist. Dabur: Board GenAI mandate FY24—zero deployed SC use cases disclosed. Marico: CTO digital transformation reference—no SC AI confirmed. Emami: No GenAI SC mention in annual report. Gartner: 74% of FMCG technology leaders cite data quality as primary AI deployment blocker.",
      clientImplication: "India FMCG technology leaders need a sequenced approach: (1) AI Readiness Diagnostic—data quality, process maturity, ERP landscape assessment; (2) Foundation Build—data governance, master data management, process standardisation; (3) Targeted AI Deployment—3-5 high-ROI use cases with measurable outcomes. Companies skipping (1) and (2) will fail at (3).",
      thoucentriqAngle: "GenAI Readiness Assessment (4 weeks): data quality audit, ERP landscape mapping, use case prioritisation framework. Output: ranked list of AI use cases with feasibility, ROI, and foundation investment required. Followed by Foundation Build programme (6-12 months) and use case implementation.",
      financialImpact: "P&G's AI investment generates estimated $500M+ in annual COGS savings from demand sensing and procurement optimisation. India mid-tier benchmark: a single AI demand sensing deployment for a ₹5,000 Cr revenue company = ₹80-150 Cr in inventory and stockout cost improvement. Foundation build investment: ₹15-30 Cr. ROI: 4-8x over 3 years.",
      whyNow: "Board-level pressure for GenAI ROI is at peak—CEO and CFO commitments made publicly in FY24. Finance teams are now reviewing 'what did GenAI deliver' in FY25 planning. Companies without a credible implementation roadmap in H1 FY25 will face board pressure and budget reallocation. This is the 12-month window for structured intervention.",
      relatedCompanies: "Dabur,Marico,Emami,Godrej CP,HUL",
      provocQuestion: "If your GenAI initiative were reviewed by the board today, what deployed SC use cases with ROI evidence would you present?",
      version: "1.0",
      nextReview: "2025-08-01",
    },
  ]);

  // ─── BENCHMARKS ──────────────────────────────────────────────────────────
  await db.insert(benchmarksTable).values([
    // SUPPLY CHAIN PLANNING
    {
      kpiName: "Demand Forecast Accuracy (DFA)",
      definition: "Percentage of demand forecast correct at SKU-location-week level. Measured as (1 - |Actual - Forecast| / Actual) × 100.",
      functionTag: "SUPPLY_CHAIN_PLANNING",
      bestInClass: ">85%",
      industryMedian: "68-72%",
      laggard: "<55%",
      unit: "%",
      sourcePeriod: "FY24",
      indiaContext: "India mid-tier FMCG average: 58-65%. HUL disclosed degradation in digital-heavy categories Q3 FY25. P&G: >85% at category level—global benchmark setter.",
      sheiAnnotation: "SHEI-2025-Q2-01",
      companyExamples: "P&G: 85%+ (best-in-class). Nestlé India: ~78% (aided by lean SKU portfolio). HUL: ~68% overall, <55% in quick-commerce categories. Marico: ~62% (Parachute over-forecast documented FY24). Dabur: ~55-60% (fragmented ERP, seasonal category volatility).",
      whyItMatters: "Every 1% improvement in DFA reduces safety stock by 1.5-2%, directly improving working capital. At 65% vs. 85% DFA, a ₹5,000 Cr FMCG company carries ~₹200-350 Cr excess inventory. DFA is the primary KPI for any demand sensing or S&OP transformation engagement.",
      consultingAngle: "Demand sensing diagnostic entry point: quantify DFA gap by channel and SKU cluster, translate to inventory and revenue impact. Immediate ROI case for demand planning transformation investment.",
      improvementLevers: "External signal integration (POS, social, weather); AI/ML demand sensing layer; S&OP cadence redesign for quick-commerce; SKU rationalisation to reduce planning complexity; channel-specific forecasting models.",
      version: "1.0",
    },
    {
      kpiName: "Perfect Order Fulfilment (OTIF)",
      definition: "Percentage of customer orders fulfilled on-time, in-full, and without quality issues. OTIF = OT% × IF% × QC%.",
      functionTag: "SUPPLY_CHAIN_PLANNING",
      bestInClass: ">95%",
      industryMedian: "82-87%",
      laggard: "<72%",
      unit: "%",
      sourcePeriod: "FY24",
      indiaContext: "India FMCG general trade OTIF: 72-80% for mid-tier. Modern trade OTIF requirement: 85-92% (retailer fines below threshold). P&G global benchmark: 94%+.",
      sheiAnnotation: "SHEI-2025-Q2-01",
      companyExamples: "P&G: 94%+ globally (benchmark setter). HUL modern trade: ~87-90%. Dabur GT: ~74-78%. Marico: ~80% overall. Emami seasonal peaks: drops to 65-70% during winter ramp-up for BoroPlus.",
      whyItMatters: "OTIF is the primary SC health metric retailers use to determine shelf allocation and collaboration. Modern trade chains (BigBazaar, DMart, Reliance Retail) apply financial penalties (0.5-2% of invoice value) for OTIF below threshold. Improving OTIF from 80% to 90% typically yields 1-2% revenue recovery from reduced penalties and improved shelf presence.",
      consultingAngle: "SC diagnostic entry: OTIF gap analysis by channel, retailer, and SKU cluster. Map root causes (forecast, manufacturing, distribution). Quantify penalty exposure and revenue risk. Create OTIF improvement programme roadmap.",
      improvementLevers: "Demand forecast accuracy improvement; manufacturing schedule adherence; distribution reliability; multi-echelon inventory optimisation; retailer collaboration programmes (VMI, CPFR).",
      version: "1.0",
    },
    {
      kpiName: "Inventory Days on Hand (DoH)",
      definition: "Average number of days of inventory held across the supply chain. Calculated as (Average Inventory / COGS per day).",
      functionTag: "SUPPLY_CHAIN_PLANNING",
      bestInClass: "28-35 days",
      industryMedian: "45-55 days",
      laggard: ">70 days",
      unit: "days",
      sourcePeriod: "FY24",
      indiaContext: "India FMCG structural context: GT distribution model requires higher inventory at redistribution stockist level (~15-20 days) vs. MT direct delivery. Modern trade VMI reduces OEM inventory days. Seasonal categories (coconut oil, cooling products) have inherently higher DoH.",
      sheiAnnotation: "SHEI-2025-Q2-01",
      companyExamples: "P&G: 32 days (best-in-class SC network design). HUL: ~40-45 days (under pressure from modern trade channel growth). Marico: DoH uptick +6 days in FY24 (Parachute over-forecasting). Dabur: 55-65 days (ERP fragmentation, seasonal category complexity). Emami: 60-70 days at seasonal peaks.",
      whyItMatters: "Inventory carrying cost = 20-25% of inventory value annually (capital, storage, obsolescence, handling). Each day of DoH reduction = ~0.3-0.5% working capital improvement. For HUL, reducing DoH from 43 to 35 days = ~₹400-600 Cr working capital release.",
      consultingAngle: "Working capital optimisation entry: DoH benchmark vs. peer group, root cause analysis (forecast, MOQ, supplier lead times, SC network), multi-echelon inventory optimisation programme. Often the gateway to demand sensing and supplier collaboration engagements.",
      improvementLevers: "Demand forecast accuracy improvement; MOQ reduction negotiation with suppliers; postponement manufacturing strategy; multi-echelon optimisation; safety stock policy redesign.",
      version: "1.0",
    },
    {
      kpiName: "Cash Conversion Cycle (CCC)",
      definition: "Days Inventory Outstanding + Days Sales Outstanding - Days Payable Outstanding. Measures working capital efficiency. Lower (even negative) is better.",
      functionTag: "SUPPLY_CHAIN_PLANNING",
      bestInClass: "-10 to +15 days",
      industryMedian: "20-35 days",
      laggard: ">50 days",
      unit: "days",
      sourcePeriod: "FY24",
      indiaContext: "India GT channel: DSO 7-14 days (cash/short credit). MT channel: DSO 45-60 days. DPO depends on supplier mix—large FMCG companies with leverage get 60-90 day terms. Quick-commerce: DSO 1-3 days (faster collection) but requires higher safety stock (higher DoH).",
      companyExamples: "HUL: CCC ~ -5 to +5 days (negative working capital model—gets paid before paying suppliers). P&G: ~-8 days. Nestlé India: ~+15 days. Dabur: ~+35 days. Emami: ~+45 days (seasonal category complexity driving DoH).",
      whyItMatters: "CCC is the CFO's primary working capital lens. A 10-day improvement in CCC for a ₹10,000 Cr revenue company = ₹270 Cr working capital release. Quick-commerce growth is directionally positive for CCC (faster collection) but increases inventory requirement—management requires integrated analysis.",
      consultingAngle: "CFO-level entry point: model CCC improvement opportunity vs. peer benchmark, map SC, procurement, and commercial levers. Often opens doors to DPO optimisation (procurement), DoH reduction (SC), and DSO management (commercial).",
      improvementLevers: "Inventory reduction (DoH); payment terms extension with suppliers (DPO); channel mix shift to faster-pay formats; reverse factoring / supply chain finance programmes.",
      version: "1.0",
    },
    // PROCUREMENT
    {
      kpiName: "Procurement Cost as % of Revenue",
      definition: "Total procurement spend (direct materials + indirect) divided by net revenue. Indicates procurement's cost weight and leverage.",
      functionTag: "PROCUREMENT",
      bestInClass: "42-46% (India FMCG)",
      industryMedian: "48-54%",
      laggard: ">58%",
      unit: "% of revenue",
      sourcePeriod: "FY24",
      indiaContext: "India FMCG direct materials are typically 40-55% of revenue (vs. 35-45% for global majors). Higher raw material intensity in India due to limited backward integration and commodity exposure (edible oils, packaging, milk solids).",
      companyExamples: "HUL: ~44% (tight cost management, negative CCC). P&G global: ~42% (best-in-class category management). Dabur: ~52% (higher natural ingredient cost structure). Marico: ~57% (Parachute is commodity-intensive). Colgate India: ~38% (lean SKU portfolio, low material complexity).",
      whyItMatters: "Procurement cost is the single largest EBIT lever in FMCG—every 1% COGS reduction = ~0.8% EBIT margin improvement for most India FMCG companies. The gap between best-in-class and median represents ₹200-800 Cr annual EBIT opportunity for a ₹10,000 Cr revenue company.",
      consultingAngle: "Procurement maturity diagnostic: spend analysis, category strategy assessment, supplier concentration risk, savings realisation tracking. Benchmark vs. peer to quantify the savings opportunity and build the transformation business case.",
      improvementLevers: "Category management programme; supplier consolidation and dual-sourcing; demand aggregation across SKUs; specification standardisation; should-cost modelling; strategic supplier partnerships.",
      version: "1.0",
    },
    {
      kpiName: "Supplier Lead Time (Critical Inputs)",
      definition: "Average days from purchase order to goods received for top-10 critical direct material inputs.",
      functionTag: "PROCUREMENT",
      bestInClass: "7-14 days",
      industryMedian: "21-35 days",
      laggard: ">45 days",
      unit: "days",
      sourcePeriod: "FY24",
      indiaContext: "India-specific context: import-dependent inputs (cocoa, fragrances, HDPE resin) have 45-90 day lead times vs. domestic alternatives. Port bottlenecks (JNPT, Chennai) add 5-10 day variability. Domestic agri commodities (copra for Marico, wheat for Britannia) have seasonal lead time dynamics.",
      companyExamples: "P&G: 9-12 days for critical inputs (advanced supplier integration). HUL: 18-25 days (domestic suppliers). Marico (Parachute copra): 25-35 days with high volatility. Reckitt: 40-55 days for imported actives (import dependency). Mondelez cocoa: 60-90 days (West Africa origin, 2024 price volatility extending lead times).",
      whyItMatters: "Lead time drives safety stock requirement—every 10-day reduction in supplier lead time reduces safety stock by 15-20% for that input category. For import-dependent categories, lead time reduction requires sourcing strategy change (alternative origins, domestic substitution) not just supplier management.",
      consultingAngle: "Supplier development programme: map lead time by input category, identify root causes (supplier location, MOQ, transport mode), design lead time reduction roadmap. Gateway to strategic sourcing and supplier partnership engagements.",
      improvementLevers: "Alternative supplier qualification (domestic vs. import substitution); consignment stocking arrangements; VMI programmes with critical suppliers; supply chain financing to ease supplier cash position; dual sourcing strategy.",
      version: "1.0",
    },
    {
      kpiName: "Supplier Concentration Risk (Top-3 Supplier Share)",
      definition: "Percentage of total spend with top-3 suppliers in a category. Higher = greater concentration risk. Best-in-class = diversified sourcing.",
      functionTag: "PROCUREMENT",
      bestInClass: "<40% with top-3",
      industryMedian: "55-65%",
      laggard: ">75%",
      unit: "% spend",
      sourcePeriod: "FY24",
      indiaContext: "India packaging landscape is highly concentrated—BOPP films: 3 suppliers dominate 70%+ of FMCG supply. Glass bottles: 2-3 regional players. This is structural, not a management choice—market depth is limited.",
      companyExamples: "HUL: ~55% top-3 concentration (managed through long-term partnerships). P&G: ~38% (global sourcing diversity). Emami packaging: ~72% (regional supplier dependency). Mondelez cocoa: Historically ~80% Barry Callebaut dependency (now diversifying post price crisis).",
      whyItMatters: "Supplier concentration amplifies the financial impact of supply disruptions. COVID-19 demonstrated: FMCG companies with >70% top-3 concentration in critical categories faced 3-6 week production stoppages. At ₹5,000 Cr revenue, a 3-week production stoppage = ₹300 Cr revenue loss.",
      consultingAngle: "Supply risk assessment: map concentration by spend category and risk-rate, quantify financial exposure from single-source dependency, design alternative supplier qualification programme. Often triggered by a near-miss disruption event.",
      improvementLevers: "Secondary supplier qualification; import vs. domestic sourcing balance; technology qualification (spec standardisation to enable multi-source); strategic inventory build for highest-risk inputs.",
      version: "1.0",
    },
    {
      kpiName: "Procurement Savings Delivered (% of Spend)",
      definition: "Realised procurement savings as % of total managed spend, measured annually. Reflects procurement function maturity and commercial leverage.",
      functionTag: "PROCUREMENT",
      bestInClass: "3-5% of spend",
      industryMedian: "1-2%",
      laggard: "<0.5%",
      unit: "% of spend",
      sourcePeriod: "FY24",
      indiaContext: "India FMCG procurement functions typically operate as transactional cost centres—annual savings target 0.5-1.5% vs. global FMCG benchmark 2-5%. Gap = ₹100-400 Cr unrealised EBIT annually for a ₹10,000 Cr revenue company.",
      sheiAnnotation: "SHEI-2025-Q2-03",
      companyExamples: "P&G global: ~3.1% of COGS (best-in-class category management). Unilever global: ~2.4%. HUL India: ~1.8% (relatively mature for India). Dabur: ~0.7% (transactional procurement). Emami: ~0.5% (no structured category management). Marico: ~1.0%.",
      whyItMatters: "Procurement savings are the highest-certainty EBIT lever available to FMCG CFOs. Unlike revenue growth (market-dependent), procurement savings are largely controllable. Each 1% savings programme = 0.5-0.8% EBIT margin improvement. Companies with best-in-class procurement generate 1.5-2.5% structural EBIT advantage vs. peers.",
      consultingAngle: "Procurement maturity assessment: benchmark current savings rate, map category management gaps, model savings opportunity by category. Business case for procurement transformation is typically 5-10x consulting investment in Year 1 savings alone.",
      improvementLevers: "Category strategy implementation; e-sourcing / RFP processes; spend analytics; should-cost modelling; supplier negotiation capability building; demand management (specification rationalisation).",
      version: "1.0",
    },
    // DISTRIBUTION & GTM
    {
      kpiName: "Distribution Reach (Outlet Coverage)",
      definition: "Percentage of total FMCG retail outlets in target geography covered by at least one direct delivery per month.",
      functionTag: "DISTRIBUTION_GTM",
      bestInClass: ">85% urban, >65% rural",
      industryMedian: "70% urban, 45% rural",
      laggard: "<55% urban, <30% rural",
      unit: "% outlets",
      sourcePeriod: "FY24",
      indiaContext: "India has ~14 million FMCG retail outlets (AC Nielsen). HUL covers ~8 million (57%). FMCG companies lose 15-25% of category potential revenue from distribution gaps. Rural penetration is the key growth lever for most India FMCG companies FY25-27.",
      companyExamples: "HUL: 8 million outlets (57% coverage); target 10 million by FY26. ITC: 7.2 million outlets (FMCG expansion ongoing). Dabur: 6.5 million; strong Ayurvedic rural. Emami: 4.8 million; seasonal category coverage intensive. Marico: 5.1 million; growing from Parachute GT base.",
      whyItMatters: "Each additional 100,000 outlet covered (at average ₹500/month per outlet) = ₹60 Cr incremental annual revenue potential. Distribution expansion is the highest-leverage growth lever for India FMCG companies in the ₹5,000-15,000 Cr revenue band.",
      consultingAngle: "RTM diagnostic: coverage mapping vs. category potential, white space identification, distributor productivity benchmarking, DTR viability assessment. GTM transformation engagement.",
      improvementLevers: "Redistribution stockist network expansion; direct-to-retailer (DTR) model for urban markets; van sales operations for rural reach; super-stockist model for low-density markets; quick-commerce channel integration.",
      version: "1.0",
    },
    {
      kpiName: "Return on Trade Spend (RoTS)",
      definition: "Revenue generated per rupee of trade promotion spend (discounts, shelf fees, displays, schemes). Reflects commercial efficiency of promotion investment.",
      functionTag: "DISTRIBUTION_GTM",
      bestInClass: ">4.5x",
      industryMedian: "2.5-3.5x",
      laggard: "<1.8x",
      unit: "x (multiplier)",
      sourcePeriod: "FY24",
      indiaContext: "India FMCG trade spend: 6-12% of net revenue (higher in modern trade, lower in GT). RoTS is chronically under-measured in India mid-tier—most companies cannot calculate it at SKU or retailer level. Modern trade requires JBP (Joint Business Planning) with retailers; 60% of India FMCG companies lack the analytics for JBP.",
      companyExamples: "P&G global: ~4.8x (AI-driven trade promo optimisation). HUL: ~3.5-4.0x (relatively strong analytics). Dabur: ~2.2x (event-driven promotions with limited ROI tracking). Marico: ~2.8x. Emami: ~1.9x (seasonal promotions often sub-optimal in timing).",
      whyItMatters: "Trade spend is typically the second-largest cost line after COGS (6-12% of revenue). A 1x improvement in RoTS = same revenue with ~20-25% less trade spend, or 20-25% more revenue with same spend. For a ₹5,000 Cr company with 8% trade spend: 1x RoTS improvement = ₹80-100 Cr annual savings or equivalent revenue opportunity.",
      consultingAngle: "Trade promotion effectiveness diagnostic: current RoTS by SKU, channel, and retailer. Identify over-investment and under-investment patterns. Design trade promotion optimisation programme using analytics and JBP frameworks.",
      improvementLevers: "Analytics platform for promotion ROI tracking; post-event analysis programme; JBP implementation with key MT accounts; promotional price elasticity modelling; shifting from blanket to targeted promotions.",
      version: "1.0",
    },
    // MANUFACTURING & QUALITY
    {
      kpiName: "Overall Equipment Effectiveness (OEE)",
      definition: "Composite measure of manufacturing efficiency: OEE = Availability × Performance × Quality. Best practice in FMCG continuous manufacturing.",
      functionTag: "MANUFACTURING",
      bestInClass: ">80%",
      industryMedian: "60-70%",
      laggard: "<50%",
      unit: "%",
      sourcePeriod: "FY24",
      indiaContext: "India FMCG OEE lags global benchmark by 10-15 points due to: frequent changeovers for small-pack SKUs, older equipment base, and unplanned downtime. Contract manufacturers typically 5-10 points below own-manufacturing OEE.",
      companyExamples: "P&G global: 82-85% (benchmark). Nestlé global: ~78%. HUL own manufacturing: ~72%. ITC foods factories: ~68%. Dabur: ~58-62% (older equipment, multi-category lines). Contract manufacturers for FMCG: 45-55%.",
      whyItMatters: "Each 1% OEE improvement for a 10-factory network at ₹500 Cr/factory throughput = ₹50 Cr additional production capacity without capex. For FMCG companies with capacity constraints, OEE improvement is both a cost and growth lever.",
      consultingAngle: "Manufacturing excellence diagnostic: OEE baselining by line and factory, Pareto of downtime causes, TPM framework design. Often the entry point for broader lean/manufacturing transformation.",
      improvementLevers: "Total Productive Maintenance (TPM) implementation; changeover time reduction (SMED); autonomous maintenance programme; spare parts management; production scheduling optimisation.",
      version: "1.0",
    },
    {
      kpiName: "First-Time Quality Rate (FTQR)",
      definition: "Percentage of production batches passing quality check on first test, without rework or rejection. Measures manufacturing quality robustness.",
      functionTag: "MANUFACTURING",
      bestInClass: ">97%",
      industryMedian: "91-95%",
      laggard: "<85%",
      unit: "%",
      sourcePeriod: "FY24",
      indiaContext: "India FMCG quality failures are amplified by: fragmented contract manufacturing base, raw material quality variability (especially agri inputs), and regulatory complexity (FSSAI compliance for foods, BIS for home care). FSSAI enforcement tightening in FY24-25.",
      companyExamples: "Nestlé India: ~97.5% (strong quality processes, lean SKU portfolio). P&G: ~98%. HUL: ~96%. Dabur Ayurvedic portfolio: ~88-92% (herbal ingredient variability). Emami seasonal production: dips to 85-87% during rapid ramp-up.",
      whyItMatters: "Rework and rejection cost = 1.5-3% of COGS for FMCG companies at 85-92% FTQR. Improving FTQR from 88% to 95% for a ₹500 Cr manufacturing cost base = ₹35-50 Cr annual savings. Plus customer complaint reduction and FSSAI compliance risk mitigation.",
      consultingAngle: "Quality management assessment: FTQR root cause analysis, incoming material quality management, in-process control point effectiveness. Links to supplier quality development and contract manufacturer management.",
      improvementLevers: "Statistical process control (SPC) implementation; incoming material quality gates; supplier quality certification; operator training; recipe/specification robustness testing.",
      version: "1.0",
    },
    // FINANCIAL METRICS
    {
      kpiName: "Gross Margin (% of Revenue)",
      definition: "Net revenue minus cost of goods sold, expressed as percentage of net revenue. Primary measure of product economics.",
      functionTag: "FINANCIAL",
      bestInClass: ">28% (India FMCG)",
      industryMedian: "18-24%",
      laggard: "<14%",
      unit: "%",
      sourcePeriod: "FY24",
      indiaContext: "India FMCG gross margin benchmark varies widely by category: Personal care (28-38%), Home care (22-28%), Foods/Beverages (15-22%), Biscuits (16-20%). Commodity cost cycles are the primary gross margin driver in India.",
      companyExamples: "Colgate India: 31.8% (highest in India FMCG—lean portfolio, premium oral care mix). HUL: ~23.4%. Godrej CP: ~20.8%. Dabur: ~18.8%. Britannia: ~17.8% (commodity-intensive biscuits). Marico: ~18.3% (Parachute commodity base).",
      whyItMatters: "Gross margin is the primary lens for procurement and SC investment ROI—every ₹1 of COGS reduction flows directly to gross margin. The commodity volatility cycle (palm oil, wheat, cocoa, packaging) creates recurring gross margin pressure requiring active procurement management.",
      consultingAngle: "Gross margin bridge analysis: decompose into volume, price, mix, and COGS components. Map COGS to procurement and manufacturing levers. Quantify the improvement opportunity from each lever to build the consulting business case.",
      improvementLevers: "Procurement cost reduction; SKU mix optimisation toward higher-margin products; pricing strategy; trade promotion efficiency; contract manufacturing vs. own manufacturing cost optimisation.",
      version: "1.0",
    },
    {
      kpiName: "Working Capital as % of Revenue",
      definition: "Net working capital (current assets minus current liabilities) divided by revenue. Measures capital efficiency of operations.",
      functionTag: "FINANCIAL",
      bestInClass: "-5% to +5%",
      industryMedian: "8-15%",
      laggard: ">20%",
      unit: "% of revenue",
      sourcePeriod: "FY24",
      indiaContext: "Negative working capital (HUL model): companies paid by customers before paying suppliers. India GT channel structurally supports low DSO (cash/7-day credit). Modern trade and e-commerce extend DSO but improve OTIF economics. Quick-commerce: DSO 1-2 days but higher inventory requirement.",
      companyExamples: "HUL: ~-2% (negative working capital—benchmark model). P&G global: ~+3%. Nestlé India: ~+8%. Dabur: ~+14% (seasonal inventory peaks, fragmented ERP driving excess DoH). Emami: ~+18-22% (high seasonal DoH for winter/summer portfolios).",
      whyItMatters: "Working capital reduction directly releases cash for reinvestment. For a ₹10,000 Cr revenue company, reducing working capital from 15% to 8% of revenue = ₹700 Cr cash release. In a rising interest rate environment (India 2023-24: 6.5% repo rate), working capital efficiency is a direct P&L lever.",
      consultingAngle: "Working capital optimisation engagement: decompose DoH, DSO, DPO gaps vs. peer benchmark. Map SC, commercial, and procurement levers. Typically generates 3-7% revenue equivalent in one-time cash release plus 0.3-0.7% annual EBIT from reduced carrying costs.",
      improvementLevers: "Inventory DoH reduction (SC transformation); DPO extension (procurement); DSO management (commercial/credit terms); supply chain finance programmes; reverse factoring.",
      version: "1.0",
    },
    // SUSTAINABILITY & COMPLIANCE
    {
      kpiName: "Scope 3 Emissions Coverage (% of Value Chain Mapped)",
      definition: "Percentage of Scope 3 upstream/downstream emissions mapped with quantified carbon estimates. Required for BRSR and CSRD compliance.",
      functionTag: "SUSTAINABILITY",
      bestInClass: ">75% mapped",
      industryMedian: "25-45%",
      laggard: "<15%",
      unit: "% value chain",
      sourcePeriod: "FY24",
      indiaContext: "SEBI BRSR: Top-1000 listed companies in India must disclose Scope 1/2 from FY23, Scope 3 from FY25. India FMCG readiness for Scope 3 mapping is low—most companies rely on spend-based estimation (low accuracy) vs. activity-based data from suppliers.",
      sheiAnnotation: "SHEI-2025-Q2-04",
      companyExamples: "Unilever global: 72% mapped (leading). P&G: 65%. HUL India: ~40% (improving; parent company methodology support). Nestlé India: ~45%. Dabur: ~18% (estimation-only). Marico: ~12% (no supplier engagement programme).",
      whyItMatters: "Scope 3 mapping is moving from a CSR metric to a procurement and supply chain operations requirement—SEBI mandates, global customer sustainability due diligence requirements, and EU CBAM (Carbon Border Adjustment Mechanism) are creating hard compliance deadlines. Companies not mapped by FY26 risk regulatory penalties and customer delisting.",
      consultingAngle: "SC sustainability diagnostic: map Scope 3 emissions by supplier tier and spend category. Identify data gaps. Design supplier engagement programme for emissions data collection. Link to procurement strategy and SC network design.",
      improvementLevers: "Supplier carbon data collection programme; procurement sustainability criteria; science-based targets alignment; renewable energy procurement; packaging recycled content targets; transportation emissions reduction (modal shift).",
      version: "1.0",
    },
  ]);

  // ─── SIGNALS ─────────────────────────────────────────────────────────────
  await db.insert(signalsTable).values([
    {
      companyName: "HUL",
      category: "EARNINGS",
      summary: "HUL Q3 FY25 results: Revenue ₹15,195 Cr (+2.4% YoY), EBITDA margin 23.4%. Management guided for 'modest volume recovery' in rural in H2 FY25. Quick-commerce now 15-16% of revenue, growing 40%+ YoY. Aging inventory flagged in Foods segment.",
      strength: "HIGH",
      action: "UPDATE_CARD",
      source: "BSE Earnings Release + Investor Call",
      eventType: "EARNINGS_RESULT",
      financialImpact: "Quick-commerce growth creating ₹200-300 Cr annual forecast accuracy gap in Foods. Rural recovery at 2% YoY is below the 6-8% required to re-accelerate revenue.",
      publishedDate: "2025-01-30",
      quarter: "Q3 FY25",
      scRelevance: "Demand forecasting for quick-commerce (SHEI-2025-Q2-01). RTM redesign urgency confirmed.",
    },
    {
      companyName: "Mondelez India",
      category: "PROCUREMENT",
      summary: "ICE Benchmark: Cocoa futures hit $10,400/ton in April 2025—3.9x the Jan 2024 price of $2,600/ton. Ghana Cocoa Board (COCOBOD) forecasts FY25 crop 650,000 tons vs. historical 900,000 tons average. Supply deficit structural for 2-3 years.",
      strength: "HIGH",
      action: "SHEI_CANDIDATE",
      source: "ICE Futures, COCOBOD Crop Report, Bloomberg Commodities",
      eventType: "MACRO_EVENT",
      financialImpact: "Mondelez India estimated EBIT impact: ₹200-300 Cr at $10,400/ton cocoa vs. $3,000/ton baseline. Every $1,000/ton cocoa price change = ~₹40-60 Cr EBIT for mid-size India confectionery player.",
      publishedDate: "2025-04-10",
      quarter: "Q4 FY25",
      scRelevance: "Procurement risk: cocoa is primary input for Cadbury/Dairy Milk, 5Star, KitKat India. Procurement strategy redesign required (SHEI-2025-Q2-02).",
    },
    {
      companyName: "Unilever",
      category: "SUPPLY_CHAIN",
      summary: "Unilever FY24 Annual Report: Confirms Ice Cream business separation (Ben & Jerry's, Magnum, Walls—€7.9B revenue) targeting completion by end 2025. Ice Cream has distinct cold-chain SC: 60,000+ freezer cabinets globally, separate 3PL network, -18°C cold chain. SC separation design is the primary execution risk.",
      strength: "HIGH",
      action: "SHEI_CANDIDATE",
      source: "Unilever FY24 Annual Report, Investor Day Presentation",
      eventType: "COMPANY_FILING",
      financialImpact: "€7.9B business being separated. SC separation cost estimated at €200-400M one-time. Post-separation: Ice Cream NewCo will need standalone SC infrastructure—cold chain capex and 3PL renegotiations.",
      publishedDate: "2025-02-12",
      quarter: "Q4 FY24",
      scRelevance: "Cold-chain SC separation design. Standalone procurement strategy for Ice Cream inputs (dairy, sugar, cocoa). Relevant benchmark for India cold-chain development.",
    },
    {
      companyName: "Dabur",
      category: "TECHNOLOGY",
      summary: "Dabur Q2 FY25 Investor Call: CFO confirms 'AI transformation' initiative has been 'expanded' with external technology partner engagement. No specific use cases disclosed. MD referenced 'data readiness as the primary prerequisite'. ERP S/4HANA migration delayed to FY26 from FY25 original timeline.",
      strength: "HIGH",
      action: "UPDATE_CARD",
      source: "NSE Earnings Call Transcript, Q2 FY25",
      eventType: "EARNINGS_RESULT",
      financialImpact: "S/4HANA migration delay costs ~₹15-20 Cr additional legacy ERP maintenance. GenAI ROI: zero confirmed deployments vs. ₹80-150 Cr potential value from demand sensing alone.",
      publishedDate: "2025-11-05",
      quarter: "Q2 FY25",
      scRelevance: "GenAI readiness gap confirmation (SHEI-2025-Q2-05). Data foundation prerequisite acknowledged by management—direct consulting entry point.",
    },
    {
      companyName: "ITC",
      category: "STRATEGY",
      summary: "ITC FMCG Segment Q3 FY25: Revenue ₹5,230 Cr (+8.1% YoY). Management confirmed e-Choupal 3.0 upgrade—integrating IoT sensors and mobile app for 6,500 kiosks to provide real-time agri procurement intelligence. S/4HANA live in 12 factories; remaining 58 by FY26.",
      strength: "MEDIUM",
      action: "UPDATE_CARD",
      source: "ITC Investor Presentation Q3 FY25",
      eventType: "EARNINGS_RESULT",
      financialImpact: "e-Choupal 3.0 investment: ₹200 Cr over 3 years. Estimated procurement savings from real-time agri pricing: ₹80-120 Cr annually. S/4HANA rollout will unlock demand sensing capabilities.",
      publishedDate: "2025-01-28",
      quarter: "Q3 FY25",
      scRelevance: "Backward integration advantage strengthening. S/4HANA rollout is the technology enabler for advanced SC planning in ITC FMCG.",
    },
    {
      companyName: "P&G",
      category: "TECHNOLOGY",
      summary: "P&G FY24 Annual Report (released Aug 2024): Disclosed 50+ GenAI use cases deployed in supply chain, manufacturing, and marketing. CSCO highlighted 'AI-driven demand sensing' as achieving >85% forecast accuracy across 90% of SKUs. Trade promotion AI delivering $200M+ savings annually.",
      strength: "HIGH",
      action: "UPDATE_CARD",
      source: "P&G FY24 Annual Report",
      eventType: "COMPANY_FILING",
      financialImpact: "P&G AI programme estimated value: $500M+ annually across demand sensing, trade promo, manufacturing. Benchmark vs. India mid-tier: 5-7 year technology gap with ₹500-2,000 Cr equivalent opportunity for each large India FMCG company.",
      publishedDate: "2024-08-09",
      quarter: "FY24",
      scRelevance: "Global SC technology benchmark. Quantifies the India FMCG GenAI implementation gap (SHEI-2025-Q2-05). Every India FMCG client engagement should reference P&G benchmarks.",
    },
    {
      companyName: "Marico",
      category: "EARNINGS",
      summary: "Marico Q3 FY25: Revenue ₹2,794 Cr (+7.4% YoY). Parachute coconut oil volumes flat vs. guidance of 4-6% growth. Management attributed to 'temporary rural demand softness'. Inventory days for Parachute increased 8 days YoY—over-forecasting continues. Saffola foods growing 19% YoY.",
      strength: "MEDIUM",
      action: "UPDATE_CARD",
      source: "Marico Earnings Release Q3 FY25",
      eventType: "EARNINGS_RESULT",
      financialImpact: "8 additional inventory days for Parachute = ~₹65 Cr excess working capital vs. previous quarter. Saffola D2C growth validating diversification but SC integration gap persisting.",
      publishedDate: "2025-01-31",
      quarter: "Q3 FY25",
      scRelevance: "Demand forecasting in seasonal/commodity categories (SHEI-2025-Q2-01). Parachute over-forecasting is a recurring pattern—documented SC diagnostic opportunity.",
    },
    {
      companyName: "Britannia",
      category: "PROCUREMENT",
      summary: "Britannia Q3 FY25: EBITDA margin expanded to 18.6% from 16.9% YoY, driven by wheat and sugar cost deflation. Management cautioned Q4 outlook given recent wheat MSP increase of ₹150/quintal by GoI. Palm oil import prices rising 8% QoQ on Indonesia export restriction signals.",
      strength: "MEDIUM",
      action: "MONITOR",
      source: "Britannia Q3 FY25 Earnings Call",
      eventType: "EARNINGS_RESULT",
      financialImpact: "Wheat MSP increase of ₹150/quintal impacts Britannia COGS by ~₹25-35 Cr annually. Palm oil import price rise: ₹40-60 Cr annual EBIT risk if sustained. Current margin tailwind may reverse in Q4 FY25.",
      publishedDate: "2025-02-05",
      quarter: "Q3 FY25",
      scRelevance: "Commodity procurement risk management for wheat and sugar. Input cost hedging strategy assessment.",
    },
    {
      companyName: "All FMCG",
      category: "REGULATORY",
      summary: "MoEFCC EPR Compliance FY25: Ministry of Environment has issued show-cause notices to 15 major FMCG companies for EPR shortfall in FY24. Fines: ₹20-50/kg of shortfall. SEBI circular (Dec 2024): Scope 3 emissions disclosure mandatory for top-1000 listed companies from FY25 annual reports.",
      strength: "HIGH",
      action: "SHEI_CANDIDATE",
      source: "MoEFCC Official Gazette, SEBI Circular CIR/CFD/CMD1/114/2024",
      eventType: "REGULATORY",
      financialImpact: "Industry-wide EPR liability at 100% enforcement: ~₹2,500 Cr/year for India FMCG. HUL estimated individual liability: ₹150-300 Cr. Scope 3 compliance infrastructure investment: ₹10-30 Cr per large FMCG company.",
      publishedDate: "2024-12-15",
      quarter: "Q3 FY25",
      scRelevance: "Sustainable packaging SC transformation (SHEI-2025-Q2-04). EPR compliance requires SC redesign, not just compliance reporting.",
    },
    {
      companyName: "Nestlé India",
      category: "STRATEGY",
      summary: "Nestlé India Analyst Day (March 2025): Announced expansion of Maggi supply chain to 12 new states by FY26. Direct distribution target increased to 5 million outlets (from current 3.8 million). ₹300 Cr capex announced for new manufacturing facility in Rajasthan to serve North/West India.",
      strength: "MEDIUM",
      action: "UPDATE_CARD",
      source: "Nestlé India Analyst Day Presentation, March 2025",
      eventType: "ANALYST_DAY",
      financialImpact: "₹300 Cr capex for Rajasthan facility. Distribution expansion to 5M outlets: ~₹600-800 Cr incremental annual revenue potential at current average outlet yield. Payback period: 3-4 years.",
      publishedDate: "2025-03-18",
      quarter: "Q4 FY25",
      scRelevance: "Distribution SC expansion for North India. Maggi demand planning complexity increase with geographic expansion.",
    },
    {
      companyName: "Colgate India",
      category: "EARNINGS",
      summary: "Colgate India Q3 FY25: Revenue ₹1,519 Cr (+9.6% YoY). EBITDA margin 32.1%—highest in India FMCG. Premium portfolio (MaxFresh, charcoal) growing 24% YoY. Management flagged competitive pressure from Patanjali Dant Kanti (gaining 3-4% rural market share) and HUL's Closeup in urban premium.",
      strength: "MEDIUM",
      action: "MONITOR",
      source: "Colgate India Q3 FY25 Earnings Call",
      eventType: "EARNINGS_RESULT",
      financialImpact: "3-4% market share loss to Patanjali in rural = ~₹60-80 Cr annual revenue risk. Premium portfolio growth partially offsetting. Import input cost exposure (fluoride, fragrance actives) rising with USD/INR at ₹84.",
      publishedDate: "2025-01-29",
      quarter: "Q3 FY25",
      scRelevance: "Import procurement cost risk. Distribution depth gap vs. Dabur Red in rural is a documented GTM weakness.",
    },
    {
      companyName: "Tata Consumer",
      category: "STRATEGY",
      summary: "Tata Consumer Products Q3 FY25: Revenue ₹4,153 Cr (+8.9% YoY). CFO disclosed post-merger ERP harmonisation (Tata Foods + Tata Beverages) 65% complete; full integration by Q2 FY26. Tea procurement synergy target ₹50 Cr annually from consolidated Assam/Darjeeling sourcing. Starbucks India: 300th store opened, breakeven model confirmed.",
      strength: "MEDIUM",
      action: "UPDATE_CARD",
      source: "Tata Consumer Q3 FY25 Earnings Call",
      eventType: "EARNINGS_RESULT",
      financialImpact: "ERP harmonisation unlocks integrated demand planning—value estimated ₹30-50 Cr in inventory reduction. Tea procurement synergy of ₹50 Cr on track. Starbucks India contribution positive from FY26.",
      publishedDate: "2025-01-30",
      quarter: "Q3 FY25",
      scRelevance: "Post-merger SC integration progress. Procurement synergy realisation from category consolidation—model for other M&A integration clients.",
    },
    {
      companyName: "All FMCG",
      category: "MACRO",
      summary: "RBI Monetary Policy Committee (Feb 2025): Repo rate cut 25bps to 6.25%—first cut in 5 years. Implications: (1) Input cost deflation expectation reducing commodity hedging urgency for some. (2) Consumer spending recovery expected to support volume recovery in mass FMCG. (3) Supply chain finance cost reduces by ~0.25%, improving DPO economics.",
      strength: "MEDIUM",
      action: "MONITOR",
      source: "RBI MPC Statement, February 2025",
      eventType: "MACRO_EVENT",
      financialImpact: "25bps rate cut: supply chain finance cost reduction = ₹15-25 Cr annual savings for a ₹5,000 Cr revenue FMCG company using SC finance on 60% of payables. Consumer demand recovery: volume tailwind expected H2 FY25.",
      publishedDate: "2025-02-07",
      quarter: "Q3 FY25",
      scRelevance: "SC finance DPO extension opportunity. Working capital optimisation economics improved. Rural demand recovery timing signal.",
    },
    {
      companyName: "Godrej CP",
      category: "STRATEGY",
      summary: "Godrej CP Investor Day 2025: Africa business now 22% of group revenue. New SC integration programme announced—Pan-Africa ERP harmonisation targeting Kenya, Nigeria, South Africa by FY27. India rural distribution: crossed 1M direct retailer touchpoints (DTR model pilot expanded).",
      strength: "MEDIUM",
      action: "UPDATE_CARD",
      source: "Godrej CP Investor Day, January 2025",
      eventType: "ANALYST_DAY",
      financialImpact: "Africa ERP harmonisation: ₹80-120 Cr investment. Expected SC savings: ₹40-60 Cr/year. DTR India pilot: 1M outlets, adding ₹150-200 Cr incremental annual revenue at current velocity.",
      publishedDate: "2025-01-15",
      quarter: "Q3 FY25",
      scRelevance: "Cross-geography SC integration. Africa SC complexity management. India DTR model expansion—SHEI-2025-Q2-01 distribution dimension.",
    },
    {
      companyName: "All FMCG",
      category: "DISRUPTION",
      summary: "Quick Commerce Disruption: Blinkit, Zepto, Swiggy Instamart combined GMV crossed $3B annualised in Q3 FY25. 10-minute delivery now standard in top-12 India cities. FMCG companies report: average order size ₹280 (vs. ₹180 in modern trade). Product assortment on q-comm: 500-2,000 SKUs vs. 10,000+ in modern trade. Category winners: energy drinks, premium snacking, personal care—not FMCG incumbents' strength.",
      strength: "HIGH",
      action: "SHEI_CANDIDATE",
      source: "Redseer Market Report Q3 FY25, Company Earnings Calls",
      eventType: "INDUSTRY_REPORT",
      financialImpact: "Q-commerce capturing 2-3% of India FMCG market (₹3,000-4,500 Cr) growing 60%+ YoY. FMCG incumbents risk losing 5-8% revenue share to D2C and new-age brands if quick-commerce curation favours new entrants. HUL q-comm revenue: ₹2,200-2,500 Cr, growing 40%+ YoY.",
      publishedDate: "2025-03-25",
      quarter: "Q4 FY25",
      scRelevance: "Quick-commerce SC readiness (SHEI-2025-Q2-01). 4-hour fulfillment requires dark store inventory pre-positioning—separate SC architecture from GT. Demand sensing failure mode if GT planning model applied.",
    },
  ]);

  // ─── PLAYBOOKS ────────────────────────────────────────────────────────────
  await db.insert(playbookSectionsTable).values([
    {
      title: "Demand Sensing & S&OP Transformation",
      functionTag: "SUPPLY_CHAIN",
      sectionNumber: 1,
      whyItMatters: "Demand planning failure is the root cause of the most expensive FMCG SC problems: excess inventory, stockouts, poor OTIF, and wasted trade spend. As quick-commerce grows to 20%+ of revenue, the gap between traditional forecasting and actual demand patterns will compound. The S&OP process is the governance mechanism—when it fails, everything downstream fails.",
      industryLandscape: "Best-in-class: P&G (>85% DFA, AI sensing with social/POS/weather), Unilever (AI sensing with external signals). India context: HUL ~68% DFA (degrading in digital); Marico ~62% (Parachute over-forecast); Dabur ~55-60% (ERP fragmentation). Quick-commerce penetration at 15-20% of revenue is the inflection point beyond which traditional statistical forecasting fails structurally.",
      failureModes: "1. Monthly forecast cadence managing 4-hour fulfillment channels. 2. No channel-specific forecasting (GT, MT, e-comm, q-comm treated as one). 3. Forecast process driven by sales targets rather than market signals. 4. S&OP divorced from financial planning. 5. No external signal integration (social, weather, POS).",
      whatGoodLooksLike: "Channel-specific sensing models; daily/weekly forecast refresh for q-comm; AI/ML layer integrating POS, social, weather; integrated S&OP connecting supply planning to financial planning; 12-18 month scenario planning capability; safety stock policies reset quarterly.",
      technologyEnablers: "o9 Solutions, Kinaxis RapidResponse, SAP IBP, Blue Yonder (JDA)—all offer AI-enhanced demand sensing. Selection depends on ERP landscape (SAP: IBP native; Oracle: Blue Yonder; greenfield: o9 or Kinaxis). GenAI use in S&OP: meeting summarisation, scenario narrative generation—supporting, not replacing, analytical capability.",
      consultingEntryPoints: "1. Demand Sensing Diagnostic (4-6 weeks): DFA baselining by channel/SKU, gap quantification in ₹. 2. S&OP Redesign: process, cadence, governance, technology selection. 3. Technology Implementation: sensing layer build and integration. 4. Change Management: training and adoption programme for new S&OP cadence.",
      status: "COMPLETE",
      version: "1.0",
    },
    {
      title: "Procurement Transformation: Transactional to Strategic",
      functionTag: "PROCUREMENT",
      sectionNumber: 2,
      whyItMatters: "Procurement is the single largest controllable EBIT lever in FMCG—representing 45-60% of revenue. Yet India FMCG procurement functions operate at Level 1-2 of the Gartner 5-level maturity model (transactional, reactive) while global peers operate at Level 3-4 (strategic, analytics-driven). The gap translates to 1.5-3% unrealised COGS savings annually—₹150-800 Cr for a mid-to-large India FMCG company.",
      industryLandscape: "P&G: 3.1% procurement savings as % of COGS (best-in-class); structured category management; supplier innovation programmes. Unilever: 2.4%; Responsible Sourcing programme. HUL India: 1.8% (relatively mature). Dabur: ~0.7%; Emami: ~0.5%—both transactional. India challenge: limited talent depth in category management; procurement not a strategic career destination vs. sales/marketing.",
      failureModes: "1. Procurement organised by supplier, not by spend category. 2. No should-cost models—negotiation based on price benchmarking, not cost decomposition. 3. Annual negotiation cycle only—no market intelligence or dynamic repricing. 4. Supplier scorecard: absent or purely logistics-focused (no innovation, quality, sustainability metrics). 5. Demand management not in scope—procurement takes specs as given.",
      whatGoodLooksLike: "Category management structure; quarterly procurement review cycle; should-cost modelling for top-10 spend categories; supplier innovation partnership programme; 3-year supplier relationship roadmap; commodity risk hedging programme; ESG/sustainability in supplier qualification.",
      technologyEnablers: "SAP Ariba (e-sourcing, contract management), Coupa (spend management), Ivalua (supplier management), GEP SMART—all are FMCG-proven. Analytics: Tableau/Power BI for spend analytics; commodity price monitoring via Bloomberg or specialist platforms (Mintec, ICIS).",
      consultingEntryPoints: "1. Procurement Maturity Assessment (3 weeks): Gartner benchmark, gap quantification, savings opportunity sizing. 2. Category Strategy Programme: 3-5 priority categories, full category management implementation. 3. Procurement Technology Roadmap: system assessment, platform selection, implementation. 4. Supplier Development: strategic supplier scorecards, innovation programme design.",
      status: "COMPLETE",
      version: "1.0",
    },
    {
      title: "Route-to-Market (RTM) Redesign for Omnichannel FMCG",
      functionTag: "SALES_DISTRIBUTION",
      sectionNumber: 3,
      whyItMatters: "India's FMCG distribution architecture—3-tier: company → superstockist → redistributor → retailer—was designed for general trade dominance (80%+ channel share in 2010). That world no longer exists. Modern trade is 15-20% of FMCG revenue, e-commerce 5-10%, quick-commerce 3-6% and growing. The same RTM model cannot efficiently serve all four channels simultaneously. Companies that redesign RTM for this new reality will gain 5-10% cost-to-serve advantage and 15-25% better in-market execution.",
      industryLandscape: "HUL: RTM reinvention 'Project Shakti' evolution + DTR pilot in urban markets; 3,500 redistribution stockists. ITC: e-Choupal integrated distribution; strong rural. Unilever global: channel-specific SC architectures per geography. Nestlé India: 8.6M outlet reach—above HUL per capita in core categories. Quick-commerce requirement: dark store pre-positioning within 2km of 10-min delivery radius.",
      failureModes: "1. Same RTM model serving general trade and modern trade (different service requirements, payment terms, pack formats). 2. No DTR viability assessment for urban markets—blanket redistribution model. 3. Rural coverage declining as distributor economics worsen. 4. Quick-commerce served from distributor stock (mismatch: daily demand variability vs. weekly resupply). 5. Channel conflict between RTM and e-commerce not resolved.",
      whatGoodLooksLike: "Channel-specific RTM architectures: GT (redistribution stockist model), MT (direct key account delivery), e-commerce (B2B fulfilment centre), q-commerce (dark store pre-positioning); distributor economic model viability check; DMS data driving route planning; DTR profitability assessment by geography.",
      technologyEnablers: "DMS: Bizom, Strawberry, Unify (India FMCG-specific). Route planning: Loginext, Routemaster. MT/KA management: SAP Trade Management, Salesforce CG Cloud. Quick-commerce integration: API connectivity with Blinkit/Zepto for demand pull.",
      consultingEntryPoints: "1. RTM Diagnostic (4-6 weeks): channel economics modelling, coverage mapping, distributor health check. 2. RTM Redesign: channel-specific architecture design, DTR pilot design. 3. Distributor Transformation: productivity improvement, DMS implementation. 4. Quick-Commerce SC Design: dark store strategy, inventory pre-positioning model.",
      status: "COMPLETE",
      version: "1.0",
    },
    {
      title: "Sustainable Supply Chain & Packaging Transformation",
      functionTag: "SUPPLY_CHAIN",
      sectionNumber: 4,
      whyItMatters: "Sustainability in FMCG SC has crossed the 'nice-to-have' threshold—it is now a compliance obligation (EPR, BRSR, CSRD) and a competitive requirement (global retail customer sustainability audits, consumer preference data). Companies that treat sustainability as a CSR cost centre will face compounding: EPR fines, customer delisting risk, and higher packaging costs from delayed recyclable material transition.",
      industryLandscape: "Global leaders: Unilever (82% recyclable packaging, 100% target 2025—likely to miss). P&G: $1B sustainable packaging fund. India: EPR enforcement tightening FY25. HUL: 99% virgin plastic reduction target by 2030; at 43% FY24. Most India FMCG mid-tier: EPR compliance reporting only—no SC redesign for recyclable packaging. Multi-layer plastic: 30% of India FMCG packaging with no cost-viable alternative at scale.",
      failureModes: "1. EPR compliance treated as a reporting exercise, not a SC design challenge. 2. Sustainable packaging R&D not connected to procurement strategy. 3. Reverse logistics / collection infrastructure absent. 4. Scope 3 emissions: spend-based estimates only (low accuracy, not compliant with BRSR Scope 3 requirements). 5. No supplier engagement for emissions data—100% estimation-driven.",
      whatGoodLooksLike: "SKU-level EPR liability mapping; supplier sustainability scorecards with carbon data; recyclable packaging roadmap by category; reverse logistics infrastructure design; Scope 3 measurement programme; science-based targets commitment.",
      technologyEnablers: "Sustainability data platforms: Watershed, Persefoni, Sweep (Scope 3 data collection). Packaging design: Dieline, Packly. Supplier carbon data: CDP, EcoVadis. Reverse logistics: specialist 3PL for packaging collection (Recykal, Karo Sambhav in India).",
      consultingEntryPoints: "1. SC Sustainability Assessment (3-4 weeks): EPR liability mapping, Scope 3 gap assessment, compliance risk quantification. 2. Sustainable Packaging Programme: SKU-level roadmap, supplier development, EPR compliance architecture. 3. Scope 3 Data Programme: supplier engagement, measurement methodology, BRSR compliance reporting.",
      status: "COMPLETE",
      version: "1.0",
    },
    {
      title: "Manufacturing Excellence & Cost Competitiveness",
      functionTag: "SUPPLY_CHAIN",
      sectionNumber: 5,
      whyItMatters: "Manufacturing is the most capital-intensive and operationally complex part of the FMCG SC. For India FMCG companies with OEE at 58-72% vs. global benchmark of 80%+, the gap represents 15-25% of untapped production capacity—equivalent to adding 3-5 factories without capex. Manufacturing excellence is the foundation for SC cost competitiveness.",
      industryLandscape: "P&G global: OEE 82-85% (benchmark). Nestlé global: ~78%. HUL India own manufacturing: ~72%. Dabur: ~58-62% (older equipment, multi-category complexity). India contract manufacturers: 45-55%. Key challenge: FMCG companies under-invest in manufacturing excellence relative to sales and marketing investment.",
      failureModes: "1. Reactive maintenance (breakdown repair) vs. preventive/predictive. 2. Long changeover times for pack-size and flavour variety (not optimised). 3. Poor spare parts management—unplanned downtime amplified by unavailability. 4. Contract manufacturer management: no formal OEE/FTQR SLAs. 5. Manufacturing not integrated with demand planning—schedule changes frequent and disruptive.",
      whatGoodLooksLike: "OEE >78% at own factories; TPM implementation with autonomous and planned maintenance; changeover times <15 min (SMED methodology); FTQR >95%; contract manufacturer performance management with quarterly reviews; manufacturing schedule stability >90%; AI-based predictive maintenance at flagship factories.",
      technologyEnablers: "MES: Siemens OPCENTER, Rockwell Automation FactoryTalk. Predictive maintenance: Azure IoT Hub, GE Predix, IBM Maximo. OEE tracking: Vorne Industries, Epicor MES. TPM digital tools: SAP PM module.",
      consultingEntryPoints: "1. Manufacturing Excellence Diagnostic (4 weeks): OEE baselining by line/factory, Pareto of loss categories, improvement opportunity sizing. 2. TPM Programme Design and Implementation: piloting at 1-2 flagship factories, then rollout. 3. Contract Manufacturer Performance Management: SLA design, audit framework, improvement programme. 4. Lean/Six Sigma Programme: waste elimination across manufacturing value stream.",
      status: "COMPLETE",
      version: "1.0",
    },
  ]);
}
